### ISSUE TITLE
WsdlXmlValidator javax.xml.stream.XMLStreamException: Prefix cannot be null

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#11]
When using a WsdlXmlValidator with a WSDL which contains a schema using the default namespace xmlns="http://www.w3.org/2001/XMLSchema" the following exception is thrown at startup:

javax.xml.stream.XMLStreamException: Prefix cannot be null
	at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeStartElement(Unknown Source)
	at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeStartElement(Unknown Source)
	at javanet.staxutils.helpers.StreamWriterDelegate.writeStartElement(StreamWriterDelegate.java:115)
	at javanet.staxutils.io.XMLWriterUtils.writeStartElement(XMLWriterUtils.java:1254)
	at javanet.staxutils.XMLStreamEventWriter.sendEvent(XMLStreamEventWriter.java:121)
	at javanet.staxutils.BaseXMLEventWriter.add(BaseXMLEventWriter.java:519)
	at nl.nn.adapterframework.validation.SchemaUtils.xsdToXmlStreamWriter(SchemaUtils.java:438)
	at nl.nn.adapterframework.validation.SchemaUtils.mergeXsdsGroupedByNamespaceToSchemasWithoutIncludes(SchemaUtils.java:195)
	at nl.nn.adapterframework.pipes.WsdlXmlValidator.getXsds(WsdlXmlValidator.java:254)
	at nl.nn.adapterframework.validation.XercesXmlValidator.init(XercesXmlValidator.java:114)
	at nl.nn.adapterframework.validation.AbstractXmlValidator.configure(AbstractXmlValidator.java:107)
	at nl.nn.adapterframework.pipes.XmlValidator.configure(XmlValidator.java:183)
	at nl.nn.adapterframework.soap.SoapValidator.configure(SoapValidator.java:47)
	at nl.nn.adapterframework.pipes.AbstractPipe.configure(AbstractPipe.java:204)
	at nl.nn.adapterframework.core.PipeLine.configure(PipeLine.java:352)
	at nl.nn.adapterframework.core.Adapter.configure(Adapter.java:161)
	at nl.nn.adapterframework.configuration.BasicAdapterServiceImpl.registerAdapter(BasicAdapterServiceImpl.java:55)
	at nl.nn.adapterframework.configuration.Configuration.registerAdapter(Configuration.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:216)
	at org.apache.commons.digester.SetNextRule.end(SetNextRule.java:217)
	at org.apache.commons.digester.Rule.end(Rule.java:253)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1222)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1785)
	at nl.nn.adapterframework.configuration.ConfigurationDigester.digestConfiguration(ConfigurationDigester.java:239)
	at nl.nn.adapterframework.configuration.ConfigurationDigester.unmarshalConfiguration(ConfigurationDigester.java:304)
	at nl.nn.adapterframework.unmanaged.DefaultIbisManager.loadConfigurationFile(DefaultIbisManager.java:76)
	at nl.nn.adapterframework.configuration.IbisContext.initConfig(IbisContext.java:76)
	at nl.nn.adapterframework.webcontrol.ConfigurationServlet.loadConfig(ConfigurationServlet.java:196)
	at nl.nn.adapterframework.webcontrol.ConfigurationServlet.init(ConfigurationServlet.java:130)
	at javax.servlet.GenericServlet.init(GenericServlet.java:160)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1228)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1147)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1043)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4957)
	at org.apache.catalina.core.StandardContext$3.call(StandardContext.java:5284)
	at org.apache.catalina.core.StandardContext$3.call(StandardContext.java:5279)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jacodg** [comment]
Fix added to Git
