### ISSUE TITLE
Larva fails on WebSphere

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1164]
**Describe the bug**
Ladybug fails on WebSphere with a null pointer exception when running Larva. 

**Reporter**
Gerrit

**Category** 
Use following Tags to categorize your bug report
 - Larva (unit test tool)
 - Ladybug

**To Reproduce**
1. Start WebSphere Docker container for iaf-test
2. Start Larva tests
4. See Null Pointer Exception

**Expected behavior**

**Screenshots**

**Environment:**
 - Application server WebSphere on Docker
 - IAF Version 7.6 d.d. 2020-10-20

**Additional context**
```
java.lang.NullPointerException
	at nl.nn.testtool.TestTool.checkpoint(TestTool.java:190)
	at nl.nn.testtool.TestTool.endpoint(TestTool.java:203)
	at nl.nn.ibistesttool.Debugger.senderOutput(Debugger.java:134)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugSenderInputOutputAbort(IbisDebuggerAdvice.java:203)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugBlockEnabledSenderInputOutputAbort(IbisDebuggerAdvice.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
	at nl.nn.adapterframework.jdbc.FixedQuerySender$$EnhancerBySpringCGLIB$$eb7bc2c8.sendMessage()
	at nl.nn.adapterframework.jdbc.JdbcSenderBase.sendMessage(JdbcSenderBase.java:118)
	at nl.nn.adapterframework.testtool.TestTool.executeFixedQuerySenderRead(TestTool.java:2752)
	at nl.nn.adapterframework.testtool.TestTool.executeStep(TestTool.java:2876)
	at nl.nn.adapterframework.testtool.TestTool.runScenarios(TestTool.java:302)
	at nl.nn.adapterframework.testtool.TestTool.runScenarios(TestTool.java:148)
	at nl.nn.adapterframework.testtool.TestTool.runScenarios(TestTool.java:134)
	at com.ibm._jsp._index._jspService(_index.java:93)

```

**Comment by gvanbrakel** [comment]
Spookrijder niet meer aangetroffen
