### ISSUE TITLE
InputStream that is replaced by getInputFromFixedValue is not closed

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#1406]
**Describe the bug**
When using Test a PipeLine to test an adapter only the stream in the message that is the result of the pipeline is closed.

**Reporter**
Jaco de Groot

**Category** 
 - Frank Console
 - Frank Framework

**To Reproduce**
1. In Frank!Runner replace examples/Frank2Example1/configurations/Example1/Configuration.xml with [Configuration.zip](https://github.com/ibissource/iaf/files/5849731/Configuration.zip) (it's in a zip because .xml cannot be added as an attachment tot this issue)

2. Add &lt;arg value="-Dlog.level=TRACE"/> to  examples/Frank2Example1/build.xml
3. Start Frank2Example1
4. Go to Test a PipeLine
5. Select adapter Example1Adapter
6. Type a dummy message and click Send
7. Go to the logfile and see that creating capture of SkipBomAndDeleteFileAfterReadInputStream is printed twice and FilterInputStream.close is printed only once.

I think this behaviour can be explained because in api/TestPipeline.java result.put("result", plr.getResult().asString()); is only called for the message that is the result of the pipeline. When the Configuration.xml contains only one file pipe and one echo pipe there's one stream opened and one stream closed.

**Expected behavior**
The number of close statements in the log should be equal to the number of creating capture statements.

**Screenshots**
\-

**Environment:**
 - Tomcat
 - H2
 - Firefox
 - FF! 7.6-20210121.133533

**Additional context**
\-

**Comment by gvanbrakel** [comment]
The problem in this setup is that the inputStream that is produced by the first FilePipe is never really consumed. It is passed on by the EchoPipe, but then it is lost, because then the second FilePipe is reached, that has a getInputFromFixedValue.

**Comment by jacodg** [comment]
While working on support for streams in Ladybug I made a mistake triggering an IndexOutOfBoundsException which also prevents the stream from being closed (using a configuration that will close the stream when no exception is thrown). This is the stacktrace:

<pre>
Caused by: java.lang.IndexOutOfBoundsException
      at java.io.StringWriter.write(StringWriter.java:90)
      at nl.nn.testtool.Checkpoint$1.write(Checkpoint.java:200)
      at org.apache.commons.io.output.WriterOutputStream.flushOutput(WriterOutputStream.java:302)
      at org.apache.commons.io.output.WriterOutputStream.close(WriterOutputStream.java:265)
      at nl.nn.adapterframework.stream.Message$1.close(Message.java:549)
      at java.io.FilterInputStream.close(FilterInputStream.java:181)
      at nl.nn.adapterframework.stream.Message$1.close(Message.java:548)
      at java.io.FilterInputStream.close(FilterInputStream.java:181)
      at nl.nn.adapterframework.stream.Message$1.close(Message.java:548)
      at java.io.FilterInputStream.close(FilterInputStream.java:181)
      at nl.nn.adapterframework.stream.Message$1.close(Message.java:548)
      at org.apache.commons.io.input.ProxyInputStream.close(ProxyInputStream.java:145)
      at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
      at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
      at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
      at java.io.InputStreamReader.close(InputStreamReader.java:199)
      at nl.nn.adapterframework.util.StreamUtil.readerToString(StreamUtil.java:133)
      at nl.nn.adapterframework.stream.Message.asString(Message.java:321)
      at nl.nn.adapterframework.stream.Message.asString(Message.java:311)
      at nl.nn.adapterframework.webcontrol.api.TestPipeline.postTestPipeLine(TestPipeline.java:118)
      ... 53 more
</pre>
