### ISSUE TITLE
JMSListener in error state does not put adapter in error/warn state in GUI

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1436]
**Describe the bug**
When having a JMSListener that cannot connect to its queue due to a permission issue, the GUI stays green and does not indicate an error. Only when unfolding the adapter with the listener or looking at logging, it is shown that there is a problem.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Have a configuration with a JmsListener that has a destination queue for which the Frank has no permissions
2. Load the configuration
3. Open the console
4. See no errors until the adapter is unfolded

**Expected behavior**
That the adapter is also shown red/yellow when one of the receivers has problems.

**Screenshots**

**Environment:**
 - Application server: [e.g. Tomcat/WebSphere/JBOSS/Jetty]: Webspher
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL]: N/A
 - Browser: [e.g. Chrome, Safari, Edge]: Chrome
 - IAF Version: [e.g. 7.5, 7.6]:7.5

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
We think it's resolved in #1354 and we don't have the intention to backport it to 7.5

**Comment by ricardovh** [comment]
> We think it's resolved in #1354 and we don't have the intention to backport it to 7.5

I still observe the described behavior in 7.6-RC1, where the adapter shows green despite the listener not being able to connect to the queue (although it is because of invalid credentials this time).

**Comment by alisihab** [comment]
Additional information: Lack of permissions does not put the receiver in STOPPED state since the onError attribute by default 'continue'.  
![image](https://user-images.githubusercontent.com/10929856/131976451-b1d3f64f-5112-4e54-a4c0-9925cc8d76f7.png)

Stacktrace:
`2021-09-03 09:15:39,790 ERROR [AsyncMessageListenerInvoker-1493] null receivers.Receiver - Receiver [JmsFFListener] Receiver [JmsFFListener] received exception [org.apache.activemq.ConnectionFailedException] from [listener of [JmsFFListener]], will continue processing messages when they arrive
org.apache.activemq.ConnectionFailedException: The JMS connection has failed: Socket closed
	at org.apache.activemq.ActiveMQConnection.checkClosedOrFailed(ActiveMQConnection.java:1436) ~[activemq-all.jar:5.6.0]
	at org.apache.activemq.ActiveMQConnection.start(ActiveMQConnection.java:502) ~[activemq-all.jar:5.6.0]
	at bitronix.tm.resource.jms.JmsConnectionHandle.start(JmsConnectionHandle.java:104) ~[btm-3.0.0-mk1.jar:3.0.0-mk1]
	at org.springframework.jms.connection.ConnectionFactoryUtils.doGetTransactionalSession(ConnectionFactoryUtils.java:331) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.connection.ConnectionFactoryUtils.getTransactionalSession(ConnectionFactoryUtils.java:140) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.connection.TransactionAwareConnectionFactoryProxy$TransactionAwareConnectionInvocationHandler.invoke(TransactionAwareConnectionFactoryProxy.java:269) ~[spring-jms-5.3.8.jar:5.3.8]
	at com.sun.proxy.$Proxy89.createSession(Unknown Source) ~[?:?]
	at org.springframework.jms.support.JmsAccessor.createSession(JmsAccessor.java:208) ~[spring-jms-5.3.8.jar:5.3.8]
	at nl.nn.adapterframework.jms.IbisMessageListenerContainer.createSession(IbisMessageListenerContainer.java:58) ~[ibis-adapterframework-core-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.access$200(AbstractPollingMessageListenerContainer.java:77) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer$MessageListenerContainerResourceFactory.createSession(AbstractPollingMessageListenerContainer.java:496) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.connection.ConnectionFactoryUtils.doGetTransactionalSession(ConnectionFactoryUtils.java:328) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:281) ~[spring-jms-5.3.8.jar:5.3.8]
	at nl.nn.adapterframework.jms.IbisMessageListenerContainer.doReceiveAndExecute(IbisMessageListenerContainer.java:93) ~[ibis-adapterframework-core-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:245) ~[spring-jms-5.3.8.jar:5.3.8]
	at nl.nn.adapterframework.jms.IbisMessageListenerContainer.receiveAndExecute(IbisMessageListenerContainer.java:87) ~[ibis-adapterframework-core-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) [spring-jms-5.3.8.jar:5.3.8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_211]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_211]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_211]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_211]
	at org.apache.activemq.transport.tcp.TcpBufferedInputStream.fill(TcpBufferedInputStream.java:50) ~[activemq-all.jar:5.6.0]
	at org.apache.activemq.transport.tcp.TcpTransport$2.fill(TcpTransport.java:602) ~[activemq-all.jar:5.6.0]
	at org.apache.activemq.transport.tcp.TcpBufferedInputStream.read(TcpBufferedInputStream.java:58) ~[activemq-all.jar:5.6.0]
	at org.apache.activemq.transport.tcp.TcpTransport$2.read(TcpTransport.java:587) ~[activemq-all.jar:5.6.0]
	at java.io.DataInputStream.readInt(DataInputStream.java:387) ~[?:1.8.0_211]
	at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:275) ~[activemq-all.jar:5.6.0]
	at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:229) ~[activemq-all.jar:5.6.0]
	at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:221) ~[activemq-all.jar:5.6.0]
	at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:204) ~[activemq-all.jar:5.6.0]
	... 1 more`

With the current implementation of IbisMessageListenerContainer it would be too difficult to determine the errors occur during receive phase. Therefore the implementation of receiving Jms messages needs to be refactor to be able to implement a mechanism that detects the receiving message is failed and retries number of times then puts the receiver in ERROR state.
