### ISSUE TITLE
Ladybug report not closed when Exception occurred while extracting the result of the PipeLine

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#1710]
**Describe the issue**

When using test a pipeline with the configuration below and changing isRepeatable() in Message.java to always return false and giving an input message that isn't an existing file name the Ladybug will say "One or more reports are finished but waiting for more than 30 seconds for one or more message capturers to close" (test a pipeline Result is: An Exception occurred while extracting the result of the PipeLine with exit state [success]: (java.io.IOException) Cannot open file [Test]).

**Reporter**
Jaco de Groot

**To Reproduce**
1. Create custom class Message.java and make isRepeatable() always return false
2. Test the configuration below with test a pipeline with an invalid file name
3. Wait 30 seconds and go to Ladybug
4. See error: One or more reports are finished but waiting for more than 30 seconds for one or more message capturers to close

**Screenshots**
\-

**Configuration**
```
		<Pipeline>
			<SenderPipe
				name="FileSenderPipe"
				>
				<LocalFileSystemSender
					action="read"
				/>
			</SenderPipe>
			<EchoPipe
				name="EchoPipe"
			/>
			<Exit path="EXIT" state="success"/>
		</Pipeline>
```

**Input**
```
Test
```

**Environment**
```
FF! 7.7-SNAPSHOT: webapp
Running on L*** using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 315M, total JVM memory: 792M
Free disk space: 209GB, total disk space: 475GB
Up since: 2021-04-15 14:22:18 (11m) 
```

**Additional Environment**
 - H2
 - Firefox

**Additional Context**
\-

**Comment by gvanbrakel** [comment]
The original exception occurs when MessageCapturer.toOutputStream() calls Message.captureBinaryStream():
```
2021-04-16 11:15:39,112 WARN  [http-nio-8080-exec-3] nl.nn.ibistesttool.MessageCapturer Could not capture message
java.io.IOException: Cannot open file [xxx]
	at nl.nn.adapterframework.stream.Message.asInputStream(Message.java:249) ~[ibis-adapterframework-core-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at nl.nn.adapterframework.stream.Message.asInputStream(Message.java:218) ~[ibis-adapterframework-core-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at nl.nn.adapterframework.stream.Message.captureBinaryStream(Message.java:533) ~[ibis-adapterframework-core-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at nl.nn.ibistesttool.MessageCapturer.toOutputStream(MessageCapturer.java:83) [ibis-adapterframework-ladybug-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at nl.nn.testtool.Checkpoint.setMessage(Checkpoint.java:268) [ibis-ladybug-2.2-20210330.112250.jar:2.2-20210330.112250]
	at nl.nn.testtool.Report.addCheckpoint(Report.java:435) [ibis-ladybug-2.2-20210330.112250.jar:2.2-20210330.112250]
	at nl.nn.testtool.Report.addCheckpoint(Report.java:370) [ibis-ladybug-2.2-20210330.112250.jar:2.2-20210330.112250]
	at nl.nn.testtool.Report.checkpoint(Report.java:294) [ibis-ladybug-2.2-20210330.112250.jar:2.2-20210330.112250]
	at nl.nn.testtool.TestTool.checkpoint(TestTool.java:257) [ibis-ladybug-2.2-20210330.112250.jar:2.2-20210330.112250]
	at nl.nn.testtool.TestTool.endpoint(TestTool.java:370) [ibis-ladybug-2.2-20210330.112250.jar:2.2-20210330.112250]
	at nl.nn.ibistesttool.Debugger.pipeOutput(Debugger.java:116) [ibis-adapterframework-ladybug-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:140) [ibis-adapterframework-ladybug-7.7-SNAPSHOT.jar:7.7-SNAPSHOT]
```
To properly handle this situation, I can think of the following approaches:
- let MessageCapturer.toOutputStream()/MessageCapturer.toWriter() throw the IOException;
- write a an error message to the outputstream/writer, and close it.
Currently, a message can be written and the outputStream/writer closed, but this close() is not detected by Ladybug
