### ISSUE TITLE
Errors when reading or resending messages from errorstore 

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1991]
**Describe the issue**
We upgraded 
from: FF! 7.6-20201118.153744 
to:     FF! 7.6-RC3-20210702.093424

When viewing or resending existing messages (created by the previous FF version) from the errorstore we get errors:
Viewing: message not found
Resending: The conversion from int to BLOB is unsupported.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/35798481/124717754-b934ae00-df05-11eb-8749-d32519827982.png)

**Configuration**
			 <errorStorage className="nl.nn.adapterframework.jdbc.JdbcTransactionalStorage"
                          name="errorStorage"
                          datasourceName="jdbc/ibis4titan"
                          slotId="Ibis4Titan/ArchiveDocumentBatch_4"/>
		       </receiver>

**Input**

**Environment**
FF! 7.6-RC3-20210702.093424: Ibis4Titan 394-1003bc34-master
Running on srtzzapp0406.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.25 - pxa6480sr6fp25-20210115_01(SR6 FP25))
Heap size: 1001M, total JVM memory: 1536M
Free disk space: 8GB, total disk space: 10GB
Up since: 2021-07-06 16:30:08 (16h)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

stacktrace from resending message : 

2021-07-07 09:19:51,994 INFO [WebContainer : 3] null interceptor.LoggingInInterceptor - Inbound Message
----------------------------
ID: 2075
Address: https://srtzzapp0406.insim.biz/ibis4titan/iaf/api/adapters/ArchiveDocumentBatch_4/receivers/ArchiveDocumentBatch_4/store/Error/message/5519494
Http-Method: GET
Content-Type:
Headers: {$WSCS=[TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384], $WSIS=[true], $WSPR=[HTTP/1.1], $WSSC=[https], $WSSI=[htShA/a1TQu5aH0/Bbb1Vg3UOad6dISe2utRDZRE29E=], $WSSN=[srtzzapp0406.insim.biz], $WSSP=[443], _WS_HAPRT_WLMVERSION=[-1], Accept=[application/json, text/plain, */*], accept-encoding=[gzip, deflate, br], Accept-Language=[en-US,en;q=0.9,ar;q=0.8,de;q=0.7,fr;q=0.6,nl;q=0.5], Authorization=[Basic Yms4OGRpOkFtc3RlcmRhbTI4], Content-Type=[null], Cookie=[_ga=GA1.2.1666412677.1542723378; _cookieSettings=%7B%22necessary%22%3Atrue%2C%22personalization%22%3Atrue%2C%22analytical%22%3Atrue%2C%22functional%22%3Atrue%7D; experimentation_subject_id=Ijc1Yzk4Y2I0LTM1ZjQtNDc0OC05NTFkLWRjZTQxOGY0MjMzZCI%3D--3543b5cc71888a40d0982b8796367e728ec0b452; 3a7e04e795ee845d2471434371c630d2=00008juVovUYxMs9fBYo4QjrP8d:-1; LtpaToken2=X4OKeBzLEwc6+O2hqFuUcq7r2ZOHp0akcPeMmVE7upulbKIbZpZo708TF7MOw6FpmBxnxS6c7PFEdCA7bgN1MWvM8SlVmAt1/7phTvsxW19HKUtndMuIp7pnwT04Pe5B0OXEBX6OKZRN56aJ+wE01iFQUqJnOTnov7VBDujQmJeq8X8iJI8jVV0YQcQFescCpt9jvAN24SLdr5lUytqy+HzNnJrW1KKmCoNlVb04sjZ6M+TTEtLxlGTCh9ud8WBXxH27JskjGmcUl7QWCx+TFK9q8vIjvW+AuoZ2rjsBBdutsK3XjXvKZH1D8K/XYKUYouH/HxrZgYN/VC/p8iJAEUErRSCRq1wuvLdzMX6lmx8=], DNT=[1], Host=[srtzzapp0406.insim.biz], Referer=[https://srtzzapp0406.insim.biz/ibis4titan/iaf/gui/], sec-ch-ua=[" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"], sec-ch-ua-mobile=[?0], Sec-Fetch-Dest=[empty], Sec-Fetch-Mode=[cors], Sec-Fetch-Site=[same-origin], Surrogate-Capability=[WS-ESI="ESI/1.0+"], User-Agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36]}
--------------------------------------
2021-07-07 09:19:51,995 INFO [WebContainer : 3] null api.AuthorizationFilter - checking authorisation for user [BK88DI] on uri [/adapters/{adapterName}/receivers/{receiverName}/store/{processState}/message/{messageId}] required roles [IbisDataAdmin, IbisAdmin, IbisTester]
2021-07-07 09:19:52,010 ERROR [WebContainer : 3] null api.ApiException - cannot deserialize message: could not extract message: (SQLServerException) The conversion from int to BLOB is unsupported.
nl.nn.adapterframework.core.ListenerException: cannot deserialize message: could not extract message: (SQLServerException) The conversion from int to BLOB is unsupported.
      at nl.nn.adapterframework.jdbc.JdbcMessageBrowser.browseMessage(JdbcMessageBrowser.java:378) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.getRawMessage(TransactionalStorage.java:551) [ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.getMessage(TransactionalStorage.java:545) [ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.browseReceiverMessage(TransactionalStorage.java:97) [ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[?:1.8.0]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
      at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
      at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at nl.nn.adapterframework.webcontrol.api.ServletDispatcher.invoke(ServletDispatcher.java:150) [ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:227) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:575) [javax.j2ee.servlet.jar:?]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1233) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:782) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:481) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:97) [com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) [ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) [ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer.jar:?]
      at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.13.1.jar:2.13.1]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4056) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1016) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:213) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892) [com.ibm.ws.runtime.jar:?]
Caused by: nl.nn.adapterframework.jdbc.JdbcException: could not extract message: (SQLServerException) The conversion from int to BLOB is unsupported.
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:837) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:147) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.jdbc.JdbcMessageBrowser.browseMessage(JdbcMessageBrowser.java:372) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      ... 60 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from int to BLOB is unsupported.
      at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.microsoft.sqlserver.jdbc.DataTypes.throwConversionError(DataTypes.java:1112) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.microsoft.sqlserver.jdbc.ServerDTVImpl.getValue(dtv.java:3704) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.microsoft.sqlserver.jdbc.DTV.getValue(dtv.java:247) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.microsoft.sqlserver.jdbc.Column.getValue(Column.java:190) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2053) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2039) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getBlob(SQLServerResultSet.java:2783) ~[mssql-jdbc-8.2.2.jre8.jar:?]
      at com.ibm.ws.rsadapter.jdbc.WSJdbcResultSet.getBlob(WSJdbcResultSet.java:760) ~[com.ibm.ws.runtime.jar:?]
      at nl.nn.adapterframework.jdbc.dbms.GenericDbmsSupport.getBlobInputStream(GenericDbmsSupport.java:305) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.util.JdbcUtil.getBlobInputStream(JdbcUtil.java:218) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:808) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:824) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:147) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      at nl.nn.adapterframework.jdbc.JdbcMessageBrowser.browseMessage(JdbcMessageBrowser.java:372) ~[ibis-adapterframework-core-7.6-RC3-20210702.093424.jar:7.6-RC3-20210702.093424]
      ... 60 more
2021-07-07 09:19:52,019 INFO [WebContainer : 3] null interceptor.LoggingOutInterceptor - Outbound Message
---------------------------
ID: 2075
Response-Code: 404
Content-Type: application/json
Headers: {Content-Type=[application/json], Date=[Wed, 07 Jul 2021 07:19:52 GMT]}
Payload: {"status":"error", "error":"cannot deserialize message: could not extract message: (SQLServerException) The conversion from int to BLOB is unsupported."}
--------------------------------------

**Comment by gvanbrakel** [comment]
Problem can be reproduced by executing iaf-test scenario '\JmsListenerSender\scenario03 - JmsFFListenerSender ERROR', and then viewing the message from the errorStorage of adapter 'JmsFFListener'
