### ISSUE TITLE
Parallel XsltSender threading issues

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2004]
**Describe the issue**
Sometimes local/ci test fail with a strange NPE. I've managed to find a stacktrace, see attached.
[nl.nn.adapterframework.xslt.ParallelXsltTest-output.txt](https://github.com/ibissource/iaf/files/6784389/nl.nn.adapterframework.xslt.ParallelXsltTest-output.txt)

-------------------------------------------------------------------------------
Test set: nl.nn.adapterframework.xslt.ParallelXsltTest

Tests run: 117, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 2.469 s <<< FAILURE! - in nl.nn.adapterframework.xslt.ParallelXsltTest
anyXmlDisableOutputEscaping[1: new, no stream: provide [false] stream out [false]](nl.nn.adapterframework.xslt.ParallelXsltTest)  Time elapsed: 0.03 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...="XsltSender"type="S[tring"><envelope>begin<disabled-elementsattr="value"/><other>&lt;enabled-elementsattr="value"/&gt;</other><disabled-elementsattr="value"/><other>&lt;enabled-elementsattr="value"/&gt;</other>end</envelope>]</result><resultsend...> but was:<...="XsltSender"type="S[enderException">XsltSender[null]Exceptionontransforminginput:(NullPointerException)]</result><resultsend...>
	at nl.nn.adapterframework.xslt.ParallelXsltTest.assertResultsAreCorrect(ParallelXsltTest.java:127)

**Reporter**
Core-Team

**Comment by gvanbrakel** [comment]
Strangest part in logging is:
```
14:10:59,607 WARN  ParallelSenderExecutor.run():60[] SenderExecutor caught exception
nl.nn.adapterframework.core.SenderException: XsltSender [null] Exception on transforming input: (NullPointerException)
	at nl.nn.adapterframework.senders.XsltSender.sendMessage(XsltSender.java:306) ~[classes/:?]
	at nl.nn.adapterframework.stream.StreamingSenderBase.sendMessage(StreamingSenderBase.java:29) ~[classes/:?]
	at nl.nn.adapterframework.senders.ParallelSenderExecutor.run(ParallelSenderExecutor.java:57) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
	at org.apache.xalan.transformer.TransformerHandlerImpl.startEntity(TransformerHandlerImpl.java:830) ~[xalan-2.7.2.jar:?]
	at nl.nn.adapterframework.xml.FullXmlFilter.startEntity(FullXmlFilter.java:105) ~[classes/:?]
	at nl.nn.adapterframework.xml.ExceptionInsertingFilter.startEntity(ExceptionInsertingFilter.java:121) ~[classes/:?]
	at nl.nn.adapterframework.xml.FullXmlFilter.startEntity(FullXmlFilter.java:105) ~[classes/:?]
	at org.apache.xerces.parsers.AbstractSAXParser.startGeneralEntity(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.handleCharacter(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:2.12.1-xml-schema-1.1]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:2.12.1-xml-schema-1.1]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:2.12.1-xml-schema-1.1]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:2.12.1-xml-schema-1.1]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
	at nl.nn.adapterframework.senders.XsltSender.sendMessage(XsltSender.java:302) ~[classes/:?]
	... 3 more
```
The NullPointerException occurs there where it is explicitly tested:
```
  public void startEntity(String name) throws SAXException
  {

    if (DEBUG)
      System.out.println("TransformerHandlerImpl#startEntity: " + name);

    if (null != m_lexicalHandler)
    {
      m_lexicalHandler.startEntity(name);
    }
  }

```

**Comment by nielsm5** [comment]
The methods argument appears to be NULL -> `m_lexicalHandler.startEntity(null);`
FullXmlFilter should check if the argument has been set. Throw a clear exception when `startEntity` is called with a null value argument.

**Comment by gvanbrakel** [comment]
After long time no see, I ran into this problem om my machine today once again.

**Comment by nielsm5** [comment]
2022-03-26 on Jenkins

**Comment by nielsm5** [comment]
2022-04-13 on Jenkins
