### ISSUE TITLE
NullPointerException on nl.nn.adapterframework.senders.ParallelSenderExecutor.run

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#2080]
### This issue is created as a log, the problem was found and solved during investigation of defect #2015

**Describe the issue**
SystemError dir contains null pointers

```
Exception in thread "WebContainer : 7/SimpleAsyncTaskExecutor-245" java.lang.NullPointerException
[28-7-21 7:37:39:312 CEST] 00000627 SystemErr R       at nl.nn.adapterframework.senders.ParallelSenderExecutor.run(ParallelSenderExecutor.java:68)
[28-7-21 7:37:39:312 CEST] 00000627 SystemErr R       at nl.nn.ibistesttool.IbisDebuggerAdvice$Executor.run(IbisDebuggerAdvice.java:432)
[28-7-21 7:37:39:312 CEST] 00000627 SystemErr R       at java.lang.Thread.run(Thread.java:822) 
A clear and concise description of what the issue is.
```

**Reporter**
JJansenvr on behalf of ibis4solife

**To Reproduce**
use an iterator with `parallel=true collectresults=false`

**Comment by jjansenvr** [comment]
Solved in commit https://github.com/ibissource/iaf/commit/4d237aeed0868ed11506229530bbbefb565abd55
