### ISSUE TITLE
Cannot create Flowdiagrams: Cannot read property "dynCall_ii" from undefined

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2196]
**Describe the issue**
Generation of flow diagrams fails with `nl.nn.adapterframework.extensions.graphviz.GraphvizException: (Exception) TypeError: Cannot read property "dynCall_ii" from undefined`

**Reporter**
Gerrit / Richard van der Stel (ibis4titan)

**To Reproduce**
1. Go to iaf-test on WebSphere
2. Look in ibis4test.log at the time of startup
3. See error like: 
```
2021-09-08 21:24:30,883 DEBUG [server.startup : 0] null flow.FlowDiagramManager - generating flow diagram for adapter[WsdlGenerator4]
2021-09-08 21:24:31,368 DEBUG [server.startup : 0] null flow.FlowDiagramManager - error generating flow diagram for [adapter[WsdlGenerator4]]
java.io.IOException: nl.nn.adapterframework.extensions.graphviz.GraphvizException: (Exception) TypeError: Cannot read property "dynCall_ii" from undefined
      at nl.nn.adapterframework.util.flow.JavaScriptFlowGenerator.generateFlow(JavaScriptFlowGenerator.java:67) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.util.flow.FlowDiagramManager.generateFlowDiagram(FlowDiagramManager.java:291) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.util.flow.FlowDiagramManager.generate(FlowDiagramManager.java:193) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]

```

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-20210907.100208: Ibis4Test
Running on srdzzapp0455 using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 412M, total JVM memory: 512M
Free disk space: 2GB, total disk space: 2GB
Up since: 2021-09-08 21:22:13 (1d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
```
2021-09-08 21:24:30,443 DEBUG [server.startup : 0] null flow.FlowDiagramManager - error generating flow diagram for [adapter[WsdlGenerator2]]
java.io.IOException: nl.nn.adapterframework.extensions.graphviz.GraphvizException: (Exception) TypeError: Cannot read property "dynCall_ii" from undefined
      at nl.nn.adapterframework.util.flow.JavaScriptFlowGenerator.generateFlow(JavaScriptFlowGenerator.java:67) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.util.flow.FlowDiagramManager.generateFlowDiagram(FlowDiagramManager.java:291) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.util.flow.FlowDiagramManager.generate(FlowDiagramManager.java:193) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.extensions.graphviz.FlowDiagramAdapterWrapper.addAdapter(FlowDiagramAdapterWrapper.java:32) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.AdapterManager.registerAdapter(AdapterManager.java:64) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.Configuration.registerAdapter(Configuration.java:396) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at sun.reflect.GeneratedMethodAccessor309.invoke(Unknown Source) ~[?:?]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
      at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
      at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:278) [commons-beanutils-1.9.4.jar:1.9.4]
      at org.apache.commons.digester3.AbstractMethodRule.invoke(AbstractMethodRule.java:245) [commons-digester3-3.2.jar:3.2]
      at org.apache.commons.digester3.AbstractMethodRule.end(AbstractMethodRule.java:192) [commons-digester3-3.2.jar:3.2]
      at org.apache.commons.digester3.Digester.endElement(Digester.java:1128) [commons-digester3-3.2.jar:3.2]
      at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.commons.digester3.Digester.parse(Digester.java:1642) [commons-digester3-3.2.jar:3.2]
      at org.apache.commons.digester3.Digester.parse(Digester.java:1745) [commons-digester3-3.2.jar:3.2]
      at nl.nn.adapterframework.configuration.ConfigurationDigester.digestConfiguration(ConfigurationDigester.java:208) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.ConfigurationDigester.digest(ConfigurationDigester.java:173) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.Configuration.configure(Configuration.java:248) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.IbisContext.createAndConfigureConfigurationWithClassLoader(IbisContext.java:369) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:294) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:247) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:130) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:95) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.lifecycle.IbisApplicationServlet.init(IbisApplicationServlet.java:79) [ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at javax.servlet.GenericServlet.init(GenericServlet.java:244) [javax.j2ee.servlet.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:342) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.init(ServletWrapperImpl.java:169) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.loadOnStartupCheck(ServletWrapper.java:1376) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebApp.doLoadOnStartupActions(WebApp.java:673) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinally(WebApp.java:639) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:454) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:171) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:904) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:789) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:427) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1249) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1591) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:708) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:1162) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:801) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.ApplicationMgrImpl$5.run(ApplicationMgrImpl.java:2325) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5536) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5662) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2330) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:436) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:379) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:127) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:985) [com.ibm.ws.runtime.jar:?]
      at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:524) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909) [com.ibm.ws.runtime.jar:?]
Caused by: nl.nn.adapterframework.extensions.graphviz.GraphvizException: (Exception) TypeError: Cannot read property "dynCall_ii" from undefined
      at nl.nn.adapterframework.extensions.graphviz.GraphvizEngine$Engine.execute(GraphvizEngine.java:198) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.extensions.graphviz.GraphvizEngine.execute(GraphvizEngine.java:97) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.util.flow.JavaScriptFlowGenerator.generateFlow(JavaScriptFlowGenerator.java:63) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      ... 62 more
Caused by: java.lang.Exception: TypeError: Cannot read property "dynCall_ii" from undefined
      at nl.nn.adapterframework.extensions.graphviz.ResultHandler.waitFor(ResultHandler.java:41) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.extensions.graphviz.GraphvizEngine$Engine.execute(GraphvizEngine.java:196) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.extensions.graphviz.GraphvizEngine.execute(GraphvizEngine.java:97) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      at nl.nn.adapterframework.util.flow.JavaScriptFlowGenerator.generateFlow(JavaScriptFlowGenerator.java:63) ~[ibis-adapterframework-core-7.7-20210907.100208.jar:7.7-20210907.100208]
      ... 62 more

```

**Comment by gvanbrakel** [comment]
Diede en Lenard zijn bezig met een alternatief om dit in de frontend te doen, voor als dit soort problemen optreden.

**Comment by jacodg** [comment]
Solved with https://github.com/ibissource/iaf/pull/3354
