### ISSUE TITLE
XSD include gives nullpointerException

### ISSUE THREAD

**Issue by Bazzu** [ibissource/iaf#2231]
**Describe the issue**

On FF version 7.7-20210921.135708, when loading the ibis4salesforce_case config jar (WebAppClassloader), three adapters give an "ERROR: got error starting Adapter (java.lang.NullPointerException): null". 

```
2021-09-22 14:32:03,322 ERROR [starting Adapter GetCasesAdapter] null core.Adapter - Adapter [GetCasesAdapter] got error starting Adapterjava.lang.NullPointerException
      at org.apache.xerces.impl.xs.traversers.XSDHandler.constructTrees(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at org.apache.xerces.parsers.XMLGrammarPreparser.preparseGrammar(Unknown Source) ~[ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
      at nl.nn.adapterframework.validation.XercesXmlValidator.preparse(XercesXmlValidator.java:227) ~[ibis-adapterframework-core-7.7-20210921.135708.jar:7.7-20210921.135708]
      at nl.nn.adapterframework.validation.XercesXmlValidator.preparse(XercesXmlValidator.java:212) ~[ibis-adapterframework-core-7.7-20210921.135708.jar:7.7-20210921.135708]
      at nl.nn.adapterframework.validation.XercesXmlValidator.start(XercesXmlValidator.java:162) ~[ibis-adapterframework-core-7.7-20210921.135708.jar:7.7-20210921.135708]
      at nl.nn.adapterframework.pipes.XmlValidator.start(XmlValidator.java:205) ~[ibis-adapterframework-core-7.7-20210921.135708.jar:7.7-20210921.135708]
      at nl.nn.adapterframework.core.PipeLine.start(PipeLine.java:522) ~[ibis-adapterframework-core-7.7-20210921.135708.jar:7.7-20210921.135708]
      at nl.nn.adapterframework.core.Adapter$1.run(Adapter.java:862) [ibis-adapterframework-core-7.7-20210921.135708.jar:7.7-20210921.135708]
      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```
All three use xsd's which all do an import on the same xsd (Generic/xsd/CommonResponse.xsd). 

It concerns the following xsd's:

- GetCaseAdapter (GetCase/xsd/GetCase.xsd)
- GetCaseDocumentsAdapter (GetCaseDocuments/xsd/GetCaseDocuments.xsd)
- GetCasesAdapter  (GetCases/xsd/GetCases.xsd)

Before the error, the following warning is found in the log files:
2021-09-22 14:32:03,341 WARN [starting Adapter GetCaseDocumentsAdapter] null validation.MyErrorHandler - XercesXmlValidator schema_reference.4: Failed to read schema document '../../Generic/xsd/CommonResponse.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

- All three xsd's and the CommonResponse.xsd are succesfully validated in XMLSpy. 
- Also, when starting this config in the Frank!Runner,  everything works without errors. 
- When the import of CommonResponse.xsd is turned off in the adapter xsd's,  the adapter starts.
- Tried 'xsd' namespace instead of 'xs' in the CommonResponse.xsd, without succes.
- We have checked for capital/lower case discrepancies (since the frankrunner/dir classloader/windows is case agnostic and the webappclassloader/java is not), and have not seen any. We do not rule out that we need new glasses/eye surgery

**Reporter**
Bastiaan. I have already spoke to Bonno, Jaco and Gerrit about this problem and was asked to create an issue.

**To Reproduce**
1. Load the config in FF version 7.7-20210921.135708 as WebAppClassloader and check logs

**Configuration**

- [Source](https://vcs.aws.insim.biz/ibissource/salesforce/ibis4salesforce/ibis4salesforce_case)
- [Jar](https://artifactory.prd.ss.aws.insim.biz/artifactory/IbisSource/org/ibissource/sf/ibis4salesforce/ibis4salesforce_case/20210922_1312-0b84be1f-main-5/)

**Environment**
```
FF! 7.7-20210921.135708: ibis4salesforce
Running on LPZWNL000022882 using Apache Tomcat/9.0.53
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 232M, total JVM memory: 1405M
Free disk space: 1GB, total disk space: 236GB
Up since: 2021-09-22 14:31:24 (9m)
```

**Additional Environment**
 - DBMS: h2
 - Browser: chrome

**Comment by gvanbrakel** [comment]
I added GetCase, GetCases and GetCaseDocuments to my configuration, and it just started up without a problem.

**Comment by gvanbrakel** [comment]
Bastiaan says:
put jar file in WEB-INF/lib directory of web-app
add properties:
IBIS="ibis4salesforce"

CONFIG="case"



TOMCAT_DIR="C:/Data/Vergaarbak/downloads/log/tomcat"

export CATALINA_HOME=${TOMCAT_DIR}

export CATALINA_OPTS="-Dinstance.name=${IBIS} \

    -DapplicationId=${IBIS} \

    -Dconsole.active=false \

    -DmanageFileSystem.active=true \

    -DmanageDatabase.webServiceListener.active=true \

    -DmanageDatabase.active=true \

    -Djdbc.migrator.active=true  \

    -Ddtap.stage=LOC \

    -Dstub4testtool.configuration=true \

    -Dibistesttool.directory=${TOMCAT_DIR}/src/test/testtool \

    -Dscenariosroot1.directory=${TOMCAT_DIR}/src/test/testtool \

    -Dscenariosroot1.description=UnitTests \

    -Dconfigurations.names=${IBIS},${CONFIG},util \

    -Dconfigurations.util.configurationFile=configurations/util/Configuration.xml \

    -Dlog.dir=${TOMCAT_DIR}/logs"

${TOMCAT_DIR}/bin/startup.bat run &

**Comment by gvanbrakel** [comment]
[ibis4xmlinclude.jar.zip](https://github.com/ibissource/iaf/files/7277554/ibis4xmlinclude.jar.zip)
base resource: caes/getCases/GetCases.xsd
ref: ../../Generic/xsd/CommonResponse.xsd
