### ISSUE TITLE
ArrayIndexOutOfBoundsException in Ladybug

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2255]
**Describe the issue**
Incidently, an ArrayIndexOutOfBoundsException appears

**Reporter**
Please state your name. If we don't know who is reporting, a solution of the issue might be delayed.

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
see [/ibissource/ibis-ladybug/issues/77]
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:424)
	at java.util.ArrayList.get(ArrayList.java:437)
	at nl.nn.testtool.Report.checkpoint(Report.java:292)
	at nl.nn.testtool.TestTool.checkpoint(TestTool.java:289)
	at nl.nn.testtool.TestTool.startpoint(TestTool.java:377)
	at nl.nn.ibistesttool.Debugger.pipeLineInput(Debugger.java:79)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:108)
	at sun.reflect.GeneratedMethodAccessor510.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$caa54419.processPipeLine(<generated>)
	at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:60)
	at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:47)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeLineProcessor.processPipeLine(CheckSemaphorePipeLineProcessor.java:58)
	at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:39)
	at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:44)
	at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:457)
	at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:679)
	at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1284)
	at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1003)
	at nl.nn.adapterframework.receivers.JavaListener.processRequest(JavaListener.java:150)
	at nl.nn.adapterframework.dispatcher.DispatcherManagerImpl.processRequest(DispatcherManagerImpl.java:123)
	at nl.nn.adapterframework.senders.IbisJavaSender.sendMessage(IbisJavaSender.java:125)
	at nl.nn.adapterframework.testtool.SenderThread.run(SenderThread.java:60)
```

**Comment by gvanbrakel** [comment]
Yes, I was using 7.7 SNAPSHOT. The error occurs 'occasionally', cannot reproduce consistently.

**Comment by jacodg** [comment]
Ok, but when it occurs, is it while running the iaf-test tests? Or you are using the Ladybug GUI to view reports? Or another situation? Does the application crash in one way or another? Or would an end user not see it except when looking into the logfile? Do you see it in de IAF logfile, the Ladybug logfile or the Tomcat console? Any context you can give might help me understand and reproduce it

**Comment by jacodg** [comment]
See https://github.com/ibissource/iaf/issues/2389
