### ISSUE TITLE
MongoDB datasource does not shutdown properly

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2467]
**Describe the issue**
MongoDB datasource does not shutdown properly. This appears to be caused by the shutdown code trying to open the datasource, just to be able to close it again. It might be interesting to see if the same kind of error also occurs on WebSphere, where the datasource is configured in another way.

**Reporter**
Gerrit

**To Reproduce**
1. Start iaf-test under tomcat, without setting active.mongodb=true
2. Stop the server
3. See error messages in console:
```
INFO: Illegal access: this web application instance has been stopped already. Could not load [com.mongodb.MongoNamespace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.mongodb.MongoNamespace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1384)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1372)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1225)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187)
	at com.mongodb.internal.connection.CommandHelper.getCommandMessage(CommandHelper.java:89)
	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83)
	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:33)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:107)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:62)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:144)
	at com.mongodb.internal.connection.DefaultServerMonitor$RoundTripTimeRunnable.initialize(DefaultServerMonitor.java:421)
	at com.mongodb.internal.connection.DefaultServerMonitor$RoundTripTimeRunnable.run(DefaultServerMonitor.java:399)
	at java.lang.Thread.run(Thread.java:745)

```
**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_41-b04)
Heap size: 214M, total JVM memory: 247M
Free disk space: 236GB, total disk space: 476GB
Up since: 2021-11-22 08:53:04 (59s)
```

**Comment by jacodg** [comment]
Let's report this to the MongoDB people
