### ISSUE TITLE
Active MQ Artemis requires ear file without log4j-jcl-2.17.0.jar

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2679]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Active MQ Artemis requires ear file without log4j-jc-2.17.0.jar

**Reporter**
Gerrit/Jo Reynaerts

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
2022-01-26 12:54:12,842 WARN [WebContainer : 3] null jms.JmsListener - [listener of [GenericReportRequest]] got exception in getPhysicalDestinationShortName
nl.nn.adapterframework.jms.JmsException: cannot create destination: could not obtain Connection: (JMSException) Failed to create connection: (ResourceAllocationException): (IllegalStateException): (NoClassDefFoundError) org.apache.activemq.artemis.utils.uri.BeanSupport (initialization failure): (LogConfigurationException): (LogConfigurationException): (LogConfigurationException) Class org.apache.commons.logging.impl.Log4JLogger does not implement Log
      at nl.nn.adapterframework.jms.JmsMessagingSource.createDestination(JmsMessagingSource.java:78) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JMSFacade.computeDestination(JMSFacade.java:342) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JMSFacade.lambda$getDestination$0(JMSFacade.java:320) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JMSFacade$$Lambda$81/0x00000000880a3d40.apply(Unknown Source) ~[?:?]
      at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1671) ~[?:1.8.0]
      at nl.nn.adapterframework.jms.JMSFacade.getDestination(JMSFacade.java:320) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JMSFacade.getDestination(JMSFacade.java:316) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JMSFacade.getPhysicalDestinationShortName(JMSFacade.java:428) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JMSFacade.getPhysicalDestinationShortName(JMSFacade.java:418) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JMSFacade.getPhysicalDestinationName(JMSFacade.java:447) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.webcontrol.api.ShowConfigurationStatus.mapAdapterReceivers(ShowConfigurationStatus.java:626) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.webcontrol.api.ShowConfigurationStatus.getAdapters(ShowConfigurationStatus.java:122) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source) ~[?:?]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
      at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
      at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at nl.nn.adapterframework.webcontrol.api.ServletDispatcher.invoke(ServletDispatcher.java:150) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:227) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [javax.j2ee.servlet.jar:?]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:143) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:96) [com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) [com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) [ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) [com.ibm.ws.webcontainer.jar:?]
      at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.0.jar:2.17.0]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:963) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382) [com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775) [com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905) [com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909) [com.ibm.ws.runtime.jar:?]
Caused by: nl.nn.adapterframework.jms.JmsException: could not obtain Connection: (JMSException) Failed to create connection: (ResourceAllocationException): (IllegalStateException): (NoClassDefFoundError) org.apache.activemq.artemis.utils.uri.BeanSupport (initialization failure): (LogConfigurationException): (LogConfigurationException): (LogConfigurationException) Class org.apache.commons.logging.impl.Log4JLogger does not implement Log
      at nl.nn.adapterframework.jms.MessagingSource.createSession(MessagingSource.java:255) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JmsMessagingSource.createDestination(JmsMessagingSource.java:75) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      ... 66 more
Caused by: javax.jms.JMSException: Failed to create connection
      at com.ibm.ejs.jms.JMSCMUtils.mapToJMSException(JMSCMUtils.java:164) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ejs.jms.JMSConnectionFactoryHandle.createConnection(JMSConnectionFactoryHandle.java:282) ~[com.ibm.ws.runtime.jar:?]
      at nl.nn.adapterframework.jms.JmsMessagingSourceFactory$ConnectionFactoryWrapper.createConnection(JmsMessagingSourceFactory.java:147) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at org.springframework.jms.connection.TransactionAwareConnectionFactoryProxy.createConnection(TransactionAwareConnectionFactoryProxy.java:142) ~[spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.adapterframework.jms.MessagingSource.createConnection(MessagingSource.java:209) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.MessagingSource.createAndStartConnection(MessagingSource.java:217) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.MessagingSource.getConnection(MessagingSource.java:225) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.MessagingSource.createSession(MessagingSource.java:253) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      at nl.nn.adapterframework.jms.JmsMessagingSource.createDestination(JmsMessagingSource.java:75) ~[ibis-adapterframework-core-7.6.3.jar:7.6.3]
      ... 66 more
```

**Environment**
```
FF! 7.6.3: ibis4solifehub
Running on xxxx using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 329M, total JVM memory: 512M
Free disk space: 2GB, total disk space: 2GB
Up since: 2022-01-24 08:24:13 (2d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Does not seem to be anything we can solve without breaking the framework logging. Can you exclude it from your ear in the pom.xml of your project?
