### ISSUE TITLE
Function "VERSION" not found stacktraces in H2 trace file

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#2712]
**Describe the issue**
When starting a Frank with jdbc.migrator.active=true like Frank2Example3 using an H2 databse a stacktrace like the following will appear in the frank2example3.trace.db:

```
2022-02-03 22:10:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "VERSION" not found; SQL statement:
select version() [90022-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:651)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.command.Parser.readFunction(Parser.java:3877)
	at org.h2.command.Parser.readTerm(Parser.java:5199)
	at org.h2.command.Parser.readFactor(Parser.java:3423)
	at org.h2.command.Parser.readSum(Parser.java:3410)
	at org.h2.command.Parser.readConcat(Parser.java:3375)
	at org.h2.command.Parser.readCondition(Parser.java:3160)
	at org.h2.command.Parser.readExpression(Parser.java:3076)
	at org.h2.command.Parser.parseSelectExpressions(Parser.java:2876)
	at org.h2.command.Parser.parseSelect(Parser.java:2893)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2783)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2650)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2629)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2622)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2615)
	at org.h2.command.Parser.parseQuery(Parser.java:2576)
	at org.h2.command.Parser.parsePrepared(Parser.java:707)
	at org.h2.command.Parser.parse(Parser.java:674)
	at org.h2.command.Parser.parse(Parser.java:644)
	at org.h2.command.Parser.prepareCommand(Parser.java:551)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:615)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:553)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:92)
	at liquibase.database.core.CockroachDatabase.isCorrectDatabaseImplementation(CockroachDatabase.java:38)
	at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:101)
	at liquibase.Liquibase.<init>(Liquibase.java:100)
	at nl.nn.adapterframework.jdbc.migration.LiquibaseMigrator.createMigrator(LiquibaseMigrator.java:99)
	at nl.nn.adapterframework.jdbc.migration.LiquibaseMigrator.createMigrator(LiquibaseMigrator.java:88)
	at nl.nn.adapterframework.jdbc.migration.LiquibaseMigrator.update(LiquibaseMigrator.java:168)
	at nl.nn.adapterframework.configuration.Configuration.runMigrator(Configuration.java:292)
	at nl.nn.adapterframework.configuration.Configuration.configure(Configuration.java:249)
	at nl.nn.adapterframework.configuration.IbisContext.createAndConfigureConfigurationWithClassLoader(IbisContext.java:366)
	at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:296)
	at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:249)
	at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:129)
	at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:94)
	at nl.nn.adapterframework.lifecycle.IbisApplicationServlet.init(IbisApplicationServlet.java:79)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1240)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1184)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1078)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5389)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5689)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1007)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:983)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2038)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Reporter**
Jaco de Groot

**To Reproduce**
1. Start Frank2Example3 with the Frank!Runner (e.g. run frank-runner\examples\Frank2Example3\build.xml in Eclipse)
2. Open frank-runner\build\h2\v2\frank2example3.trace.db in a text editor
3. See the stacktrace at the end of the file

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 7.7-20220202.144505: Frank2Example3
Running on xxx using Apache Tomcat/7.0.103
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 208M, total JVM memory: 512M
Free disk space: 165GB, total disk space: 475GB
Up since: 2022-02-03 22:10:25 (9m) 
```

**Additional Environment**
 \-

**Additional Context**
\-

**Comment by alisihab** [comment]
This seems to be a bug in liquibase. The function should be H2VERSION (http://www.h2database.com/html/functions.html#h2version). I created a ticket in liquibase repo

**Comment by alisihab** [comment]
There is a newer version of liquibase that addresses a fix for this issue
