### ISSUE TITLE
Using Stub is yes in Ladybug for Json2XmlValidator keeps report in progress

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#3065]
**Describe the issue**
Using Stub is yes in Ladybug for Json2XmlValidator keeps report in progress. When you open the report in progress it shows:

Message of type nl.nn.adapterframework.core.PipeRunException is encoded to string using printStackTrace()
```
nl.nn.adapterframework.core.PipeRunException: Uncaught runtime exception running pipe 'Transform XML message to JSON message': (ClassCastException) java.lang.String cannot be cast to nl.nn.adapterframework.stream.Message
	at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:87)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:234)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:122)
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$821ea2fe.processPipeLine(<generated>)
	at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:60)
	at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:47)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeLineProcessor.processPipeLine(CheckSemaphorePipeLineProcessor.java:58)
	at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:41)
	at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:44)
	at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:470)
	at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:649)
	at nl.nn.adapterframework.core.Adapter.processMessage(Adapter.java:558)
	at nl.nn.ibistesttool.Debugger.rerun(Debugger.java:268)
	at nl.nn.testtool.TestTool.rerun(TestTool.java:836)
	at nl.nn.testtool.TestTool.rerun(TestTool.java:804)
	at nl.nn.testtool.echo2.reports.MessageComponent.actionPerformed(MessageComponent.java:436)
	at nl.nn.testtool.echo2.reports.CheckpointComponent.actionPerformed(CheckpointComponent.java:294)
	at nextapp.echo2.app.button.AbstractButton.fireActionPerformed(AbstractButton.java:135)
	at nextapp.echo2.app.button.AbstractButton$1.actionPerformed(AbstractButton.java:100)
	at nextapp.echo2.app.button.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:70)
	at nextapp.echo2.app.button.DefaultButtonModel.doAction(DefaultButtonModel.java:58)
	at nextapp.echo2.app.button.AbstractButton.doAction(AbstractButton.java:121)
	at nextapp.echo2.app.button.AbstractButton.processInput(AbstractButton.java:506)
	at nextapp.echo2.app.update.ClientUpdateManager.process(ClientUpdateManager.java:116)
	at nextapp.echo2.app.update.UpdateManager.processClientUpdates(UpdateManager.java:89)
	at nextapp.echo2.webcontainer.ContainerSynchronizeService.renderUpdate(ContainerSynchronizeService.java:471)
	at nextapp.echo2.webrender.service.SynchronizeService.service(SynchronizeService.java:279)
	at nextapp.echo2.webrender.WebRenderServlet.process(WebRenderServlet.java:273)
	at nextapp.echo2.webrender.WebRenderServlet.doPost(WebRenderServlet.java:189)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to nl.nn.adapterframework.stream.Message
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:138)
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$9f6b0cde.processPipe(<generated>)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.ExceptionHandlingPipeProcessor.processPipe(ExceptionHandlingPipeProcessor.java:38)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:77)
	... 77 more
```
I think this is the result of the fix for #3035

**Reporter**
Jaco de Groot

**To Reproduce**
1. Use the config below in an adapter
2. Use test a pipeline with this adapter
3. Open the report in Ladybug
4. On the input of this pipe change Stub from Follow report strategy to Yes
5. Click Rerun
6. Open the new report
7. See error

**Screenshots**
\-

**Configuration**
```
			<Json2XmlValidatorPipe
				name="Transform XML message to JSON message"
				noNamespaceSchemaLocation="HelloLines/xsd/Lines.xsd"
				root="lines"
				outputFormat="JSON"
				preserveInput="true"
				storeResultInSessionKey="exampleMessageAsJson"
				throwException="true"
				>
				<Forward name="success" path="Remove namespaces"/>
			</Json2XmlValidatorPipe>
```

**Input**
```
<lines><line1>Line One</line1><line2>Line Two</line2><line3>Line Three</line3><line4>Line Four</line4><line5>Line Five</line5></lines>
```

**Environment**
```
FF! 7.8-20220414.093607: Frank2Example4
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 312M, total JVM memory: 795M
Free disk space: 82GB, total disk space: 475GB
Up since: 2022-04-14 14:02:58 (12m) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by nielsm5** [comment]
See https://github.com/ibissource/ibis-ladybug/issues/121
