### ISSUE TITLE
Ibis4TestIAF out of memory at startup

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#3295]
**Describe the issue**
Ibis4TestIAF run into out-of-memory at startup, appearantly while generating flow diagrams.
Subsequently, JdbcFacade.getDatasource() runs into a NullPointerException in ConcurrentHashMap.computeIfAbsent(). This occurs repeatedly in getPhysicalDestinationName() in showConfigurationStatus()

**Reporter**
Gerrit

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220601.133926: Ibis4Test
Running on xxxx using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 481M, total JVM memory: 512M
Free disk space: 859MB, total disk space: 2GB
Up since: 2022-06-02 10:12:45 (37m)
```

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)
```
SystemOut:
[2-6-22 10:12:44:995 CEST] 0000005b webapp I com.ibm.ws.webcontainer.webapp.WebApp log SRVE0292I: Servlet Message - [wasap18_Ibis4TestIAF#ibis4testiaf.war]:.Starting IbisContext
[2-6-22 10:14:50:473 CEST] 0000002b FfdcProvider I FFDC provider error
java.lang.OutOfMemoryError: Java heap space
      at com.ibm.ffdc.impl.Ffdc.setFailsafeProvider(Ffdc.java:138)
      at com.ibm.ffdc.impl.Ffdc.abort(Ffdc.java:159)
      at com.ibm.ffdc.util.provider.FfdcProvider.abort(FfdcProvider.java:394)
      at com.ibm.ws.ffdc.impl.FfdcProvider.logIncident(FfdcProvider.java:193)
      at com.ibm.ws.ffdc.impl.FfdcProvider.logIncident(FfdcProvider.java:145)
      at com.ibm.ffdc.util.provider.FfdcProvider.log(FfdcProvider.java:289)
      at com.ibm.ffdc.util.provider.FfdcProvider.log(FfdcProvider.java:266)
      at com.ibm.ws.ffdc.impl.FfdcProvider.log(FfdcProvider.java:257)
      at com.ibm.ffdc.util.provider.IncidentEntry.log(IncidentEntry.java:106)
      at com.ibm.ffdc.util.provider.Ffdc.log(Ffdc.java:96)
      at com.ibm.ffdc.util.provider.FfdcProvider.log(FfdcProvider.java:351)
      at com.ibm.ffdc.impl.Ffdc.log(Ffdc.java:225)
      at com.ibm.ejs.util.am.AlarmThreadMonitor$AlarmThreadCheckDetector.run(AlarmThreadMonitor.java:433)
      at java.lang.Thread.run(Thread.java:825)

[2-6-22 10:14:50:495 CEST] 00000023 SystemOut O ::
[2-6-22 10:14:50:496 CEST] 00000023 SystemOut O R/,
```
ibis4test.log:
```
2022-05-30 10:00:02,496 DEBUG [WebContainer : 5] null flow.FlowDiagramManager - generating flow diagram for configuration [IAF_Util]
2022-05-30 10:00:02,499 DEBUG [WebContainer : 5] null graphviz.GraphvizEngine - Setting Graphviz options to [nl.nn.adapterframework.util.flow.graphviz.Options@310d76b8 - engine[dot] format[SVG] memory[null] yInvert[null]]
2022-05-30 10:00:02,499 DEBUG [WebContainer : 5] null graphviz.GraphvizEngine - creating new VizJs engine
2022-05-30 10:00:03,249 DEBUG [WebContainer : 5] null GraphvizEngine.Engine - Trying Javascript engine [nl.nn.adapterframework.extensions.javascript.Nashorn] for Graphviz.
2022-05-30 10:00:03,249 INFO  [WebContainer : 5] null GraphvizEngine.Engine - Starting runtime for Javascript Engine...
2022-05-30 10:00:03,270 INFO  [WebContainer : 5] null GraphvizEngine.Engine - Started Javascript Engine runtime. Initializing Graphviz...
2022-05-30 10:00:56,589 WARN  [WebContainer : 5] null flow.DotFlowGenerator - failed to initalize IFlowGenerator
java.lang.OutOfMemoryError: Java heap space
	at jdk.nashorn.internal.ir.BlockLexicalContext.push(BlockLexicalContext.java:64) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:68) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.CaseNode.accept(CaseNode.java:112) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.ForNode.accept(ForNode.java:110) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextStatement.accept(LexicalContextStatement.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LoopNode.accept(LoopNode.java:48) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.IfNode.accept(IfNode.java:101) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.WhileNode.accept(WhileNode.java:97) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextStatement.accept(LexicalContextStatement.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LoopNode.accept(LoopNode.java:48) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LabelNode.accept(LabelNode.java:92) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextStatement.accept(LexicalContextStatement.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LabelNode.accept(LabelNode.java:48) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.IfNode.accept(IfNode.java:101) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.IfNode.accept(IfNode.java:101) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.IfNode.accept(IfNode.java:101) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.WhileNode.accept(WhileNode.java:97) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextStatement.accept(LexicalContextStatement.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LoopNode.accept(LoopNode.java:48) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LabelNode.accept(LabelNode.java:92) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextStatement.accept(LexicalContextStatement.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LabelNode.accept(LabelNode.java:48) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:348) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:59) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:348) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:76) ~[nashorn.jar:?]
	at jdk.nashorn.internal.codegen.SplitIntoFunctions.enterVarNode(SplitIntoFunctions.java:331) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.VarNode.accept(VarNode.java:179) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:451) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.SplitNode.accept(SplitNode.java:102) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextStatement.accept(LexicalContextStatement.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.SplitNode.accept(SplitNode.java:50) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.CallNode.accept(CallNode.java:191) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.CallNode.accept(CallNode.java:191) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:348) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:76) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Node.accept(Node.java:283) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.Block.accept(Block.java:197) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at <unknown class>.<unknown method>(Unknown Source) ~[?:?]
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:69) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:59) ~[nashorn.jar:?]
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:640) ~[nashorn.jar:?]
	at jdk.nashorn.internal.codegen.CompilationPhase.access$100(CompilationPhase.java:67) ~[nashorn.jar:?]
	at jdk.nashorn.internal.codegen.CompilationPhase$SplittingPhase.transform(CompilationPhase.java:141) ~[nashorn.jar:?]
	at jdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:636) ~[nashorn.jar:?]
	at jdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:667) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1329) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1263) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:639) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:547) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:536) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:414) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:167) ~[nashorn.jar:?]
	at nl.nn.adapterframework.extensions.javascript.Nashorn.executeScript(Nashorn.java:69) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.graphviz.GraphvizEngine$Engine.startEngine(GraphvizEngine.java:222) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.graphviz.GraphvizEngine$Engine.<init>(GraphvizEngine.java:203) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.graphviz.GraphvizEngine.getEngine(GraphvizEngine.java:154) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.graphviz.GraphvizEngine.<init>(GraphvizEngine.java:73) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.graphviz.GraphvizEngine.<init>(GraphvizEngine.java:57) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.GraphvizJsFlowGenerator.createGraphvizEngine(GraphvizJsFlowGenerator.java:57) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.GraphvizJsFlowGenerator.getGraphvizEngine(GraphvizJsFlowGenerator.java:43) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.GraphvizJsFlowGenerator.generateFlow(GraphvizJsFlowGenerator.java:69) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.FlowDiagramManager.generateFlowDiagram(FlowDiagramManager.java:238) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.util.flow.FlowDiagramManager.generate(FlowDiagramManager.java:159) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.configuration.Configuration.configure(Configuration.java:262) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.configuration.IbisContext.createAndConfigureConfigurationWithClassLoader(IbisContext.java:367) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:297) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:250) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:130) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:95) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.configuration.IbisContext.fullReload(IbisContext.java:232) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.unmanaged.DefaultIbisManager.handleAction(DefaultIbisManager.java:236) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at nl.nn.adapterframework.webcontrol.api.ShowConfiguration.fullReload(ShowConfiguration.java:125) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[?:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.4.7.jar:3.4.7]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.4.7.jar:3.4.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[cxf-rt-frontend-jaxrs-3.4.7.jar:3.4.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[cxf-rt-frontend-jaxrs-3.4.7.jar:3.4.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.4.7.jar:3.4.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.4.7.jar:3.4.7]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[cxf-core-3.4.7.jar:3.4.7]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.4.7.jar:3.4.7]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at nl.nn.adapterframework.webcontrol.api.ServletDispatcher.invoke(ServletDispatcher.java:149) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:234) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[javax.j2ee.servlet.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[cxf-rt-transports-http-3.4.7.jar:3.4.7]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:143) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:96) ~[com.ibm.ws.webcontainer.jar:?]
	at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
	at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.17.2.jar:2.17.2]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4238) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.handleRequest(WebAppImpl.java:2210) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1033) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905) ~[com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909) ~[com.ibm.ws.runtime.jar:?]
2022-05-30 10:00:56,860 WARN  [WebContainer : 5] null configuration.Configuration - Configuration [IAF_Util] Error generating flow diagram for configuration [IAF_Util]
java.lang.NullPointerException
	at nl.nn.adapterframework.util.flow.GraphvizJsFlowGenerator.generateFlow(GraphvizJsFlowGenerator.java:69) ~[ibis-adapterframework-core-7.8-20220527.160303.jar:7.8-20220527.160303]
```

**Comment by nielsm5** [comment]
The beforementioned pr fixes an NPE but not the OOM Exception. Can you try using the J2V8 engine instead?
