### ISSUE TITLE
Receiver with ESBJMSListener keeps processing while adapter is in error (7.7.2)

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#3548]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We noticed that a receiver with an ESBJMSListener keeps retrieving messages from the queue, but throws them directly in the errorstore with errormessage:
Adapter [ArchiveDocumentBatch_4] in state [ERROR], cannot process message

We see in the heartbeat.log that the adapter has state error and the receiver only has a warning :   

2022-08-07 06:01:51,794 ERROR adapter [ArchiveDocumentBatch_4] has state [ERROR]
2022-08-07 06:01:51,794 WARN  receiver [ArchiveDocumentBatch_4_Receiver] of adapter [ArchiveDocumentBatch_4] has state [STOPPED]
2022-08-07 06:01:51,794 WARN  receiver [ArchiveDocumentBatch_4_Receiver_Retry] of adapter [ArchiveDocumentBatch_4] has state [STOPPED]

We think that the receiver should not get messages from the queue when the adapter cannot process them.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by rvdstel** [comment]
We see in the log file that these are the first errors occurring: 

2022-08-07 00:00:00,545 WARN [ArchiveDocumentBatch_4_Receiver[5]] null jms.IbisMessageListenerContainer - Rejecting received message because of the listener container having been stopped in the meantime: TextMessage={ Header={ JMSMessageID={ID:EMS_PRD_ESB_LARGE.1AB562D51B8D37F1B208:4289666}

JMSDestination={Queue[ESB.Archiving.TS.Document.4.ArchiveDocumentBatch.1.Action]} JMSReplyTo={null} JMSDeliveryMode={PERSISTENT} JMSRedelivered={false} JMSCorrelationID={ID:EMS_PRD_P2P_LARGE.E9D62CAB89D352636ED:1023174} JMSType={null} JMSTimestamp={Sat Aug 06 16:08:07 CEST 2022} JMSDeliveryTime={Sat Aug 06 16:08:07 CEST 2022} JMSExpiration={0} JMSPriority={4} } Properties={ JMSXDeliveryCount={Integer:1} SoapAction={String:ArchiveDocumentBatch_1} }

and next an error in a subadapter : 

2022-08-07 00:00:01,432 ERROR [ArchiveDocumentBatch_4_Receiver[8]] [mid [ID:EMS_PRD_P2P_LARGE.E9D62CAB89D352636E4:1023165]] receivers.Receiver - Receiver [NotifyDocumentCall] Exception in message processing nl.nn.adapterframework.core.ListenerException: Pipe [putNotificationOnQueue] msgId [ID:EMS_PRD_P2P_LARGE.E9D62CAB89D352636E4:1023165] caught exception: could not obtain Connection: (JMSException) Failed to create connection: (ConnectionWaitTimeoutException) Connection not available got InterruptedException while waiting at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:679) ~[ibis-adapterframework-core-7.7.2.jar:7.7.2] at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1290) ~[ibis-adapterframework-core-7.7.2.jar:7.7.2] at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1001) ~[ibis-adapterframework-core-7.7.2.jar:7.7.2]

Between these timestamps in the heartbeat, the errors should have begun: 
2022-08-06 23:56:51,796 INFO [103/103] adapters and [107/107] receivers have state [STARTED]
2022-08-07 00:01:51,797 INFO [101/103] adapters and [103/107] receivers have state [STARTED]

So far we cannot see why the listener container was stopped.
