### ISSUE TITLE
Httpsender doesn't work for uploading files to microsoft sharepoint

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#3653]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We have an ibis app which uploads files to sharepoint. But with the normal http sender configured for a POST method with multipartxml doesn't work and gets the following error:

```txt
nl.nn.adapterframework.core.SenderException: HttpSender [Send_To_Sharepoint-sender] httpstatus [500] reason [Internal Server Error] body [<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, System.IO.IOException</m:code><m:message xml:lang="en-US">I/O error occurred.</m:message></m:error>]
	at nl.nn.adapterframework.http.HttpSender.extractResult(HttpSender.java:535)
	at nl.nn.adapterframework.http.HttpSenderBase.sendMessage(HttpSenderBase.java:692)
	at nl.nn.adapterframework.http.HttpSenderBase$$FastClassBySpringCGLIB$$f73d91f3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugSenderInputOutputAbort(IbisDebuggerAdvice.java:221)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugSenderInputOutputAbort(IbisDebuggerAdvice.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
response from sharepoint
```xml
<?xml version="1.0" encoding="utf-8"?>
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
	<m:code>-1, System.IO.IOException</m:code>
	<m:message xml:lang="en-US">I/O error occurred.</m:message>
</m:error>
```
It does work with the attached custom httpsender
[SharePointHttpSender.zip](https://github.com/ibissource/iaf/files/9494667/SharePointHttpSender.zip)

**Reporter**
Vinh

**To Reproduce**

1. Configure attached adapter configuration 
[Configuration_Test.zip](https://github.com/ibissource/iaf/files/9494953/Configuration_Test.zip)

2. Contact me for property values of the adapter
3. Test this adapter via test a pipeline, input can be dummy string
5. Replace pipe Send_To_Sharepoint with aforementioned custom SharePointHttpSender and then it will work

Note: please test from an NN workstation

**Environment**
```
FF! 7.7.3: Ibis4Scan
Running on LPZWNL000033000 using Apache Tomcat/8.5.40
Java Version: Java(TM) SE Runtime Environment (1.8.0_172-b11)
Heap size: 325M, total JVM memory: 729M
Free disk space: 13GB, total disk space: 236GB
Up since: 2022-09-06 09:04:07 (1h)
```

**Comment by gvanbrakel** [comment]
It appears the following configuration works in 7.8-RC1:
```
	<sender 
		allowSelfSignedCertificates="true"
		className="nl.nn.adapterframework.http.HttpSender"
		timeout="120000"
		urlParam="sharepointUrl"
		verifyHostname="false"
		headersParams="Authorization"
		contentType=""
		methodType="POST"
		postType="BINARY"
	>
```

**Comment by VBPham** [comment]
yes files can be send to sharepoint using httpsender with the configuration Gerrit mentioned
