### ISSUE TITLE
IncompatibleClassChangeError in combination of Narayana and ActiveMQ artemis

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#3721]
**Describe the issue**
When running with Narayana and ActiveMQ artemis, the log is filled with IncompatibleClassChangeErrors.

**Reporter**
Gerrit

**To Reproduce**
1. run iaf-test with Narayana and ActiveMQ artemis, and active.jms=true
4. See errors in console

**Screenshots**
```
2022-09-15 10:48:27,937 WARN  [AsyncMessageListenerInvoker-297] null ats.arjuna - ARJUNA012129: TwoPhaseCoordinator.afterCompletion - failed for SynchronizationImple< 0:ffff0a7258b1:d0fd:6322e390:28f6, org.jboss.narayana.jta.jms.SessionClosingSynchronization@1073936 > with error
java.lang.IncompatibleClassChangeError: Class org.apache.activemq.artemis.jms.client.ActiveMQXASession does not implement the requested interface java.lang.AutoCloseable
	at org.jboss.narayana.jta.jms.SessionClosingSynchronization.afterCompletion(SessionClosingSynchronization.java:63) ~[narayana-jta-5.12.7.Final.jar:5.12.7.Final (revision: bd3d5)]
	at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.afterCompletion(SynchronizationImple.java:96) ~[narayana-jta-5.12.7.Final.jar:5.12.7.Final (revision: bd3d5)]
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.afterCompletion(TwoPhaseCoordinator.java:545) ~[narayana-jta-5.12.7.Final.jar:5.12.7.Final (revision: bd3d5)]
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:101) ~[narayana-jta-5.12.7.Final.jar:5.12.7.Final (revision: bd3d5)]
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162) ~[narayana-jta-5.12.7.Final.jar:5.12.7.Final (revision: bd3d5)]
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295) ~[narayana-jta-5.12.7.Final.jar:5.12.7.Final (revision: bd3d5)]
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128) ~[narayana-jta-5.12.7.Final.jar:5.12.7.Final (revision: bd3d5)]
	at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1035) ~[spring-tx-5.3.22.jar:5.3.22]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx-5.3.22.jar:5.3.22]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx-5.3.22.jar:5.3.22]
	at nl.nn.adapterframework.jta.SpringTxManagerProxy.commit(SpringTxManagerProxy.java:70) ~[ibis-adapterframework-core-7.9-SNAPSHOT.jar:7.9-SNAPSHOT]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) ~[spring-jms-5.3.22.jar:5.3.22]
	at nl.nn.adapterframework.jms.IbisMessageListenerContainer.receiveAndExecute(IbisMessageListenerContainer.java:87) ~[ibis-adapterframework-core-7.9-SNAPSHOT.jar:7.9-SNAPSHOT]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.22.jar:5.3.22]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.22.jar:5.3.22]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.22.jar:5.3.22]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]

```

**Environment**
```
FF! 7.9-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_312-b07)
Heap size: 341M, total JVM memory: 545M
Free disk space: 93GB, total disk space: 476GB
Up since: 2022-09-15 10:54:51 (50s)
```

**Additional Environment**
 - DBMS: Oracle

**Comment by nielsm5** [comment]
Can't reproduce this.. Perhaps you had an older version of ActiveMQ on your classpath?
