### ISSUE TITLE
HttpSender connection pool deadlock on parallel processing

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3947]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using a HttpSender in a ParallelSender that is running in multiple threads, there is the risk of getting `nl.nn.adapterframework.core.SenderException: (ConnectionPoolTimeoutException) Timeout waiting for connection from pool`

Observed in 7.7.3 and 7.9-20221027.201216.

**Reporter**
Ricardo

**To Reproduce**
1. Load below adapters
2. Go to test a pipeline
3. Put in a message to Main with lots of child elements (I tested with +- 100 child elements just to be sure, but the issue should also occur at lower numbers)
4. Get ConnectionPoolTimeoutException for most HttpSender calls

I tested without the ParallelSender and just a single HttpSender and with a single HttpSender in the ParallelSender, the issue did not occur then, so I suspect having multiple HttpSenders in the ParallelSender is key to the issue. Limiting maxChildThreads also prevents the issue (no extensive testing as to which value will give the issue and which ones will not)

**Screenshots**

**Configuration**
```
<Module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../FrankConfig.xsd">	
	<Adapter name="Main">
		<Receiver name="Main">
			<JavaListener name="Main"/>
		</Receiver>

		<Pipeline>
			<Exits>
				<Exit name="EXIT" state="SUCCESS" />
			</Exits>

			<ForEachChildElementPipe name="CallChild"
				parallel="true"
				maxChildThreads="0">
				<IbisLocalSender javaListener="Child"/>
				<Forward name="success" path="EXIT" />
			</ForEachChildElementPipe>
		</Pipeline>
	</Adapter>
	
	<Adapter name="Child">
		<Receiver name="Child">
			<JavaListener name="Child"/>
		</Receiver>

		<Pipeline>
			<Exits>
				<Exit name="EXIT" state="SUCCESS" />
			</Exits>

			<SenderPipe name="ParallelSender">
				<ParallelSendersSender>
					<HttpSender url="http://localhost/iaf/api/server/health"/>
					<HttpSender url="http://localhost/iaf/api?allowedRoles=true"/>
					<HttpSender url="http://localhost/iaf/api/environmentvariables"/>
				</ParallelSendersSender>
				<Forward name="success" path="EXIT" />
			</SenderPipe>
		</Pipeline>
	</Adapter>
</Module>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Stacktrace:
`nl.nn.adapterframework.core.SenderException: (ConnectionPoolTimeoutException) Timeout waiting for connection from pool
	at nl.nn.adapterframework.http.HttpSenderBase.sendMessageAndProvideForwardName(HttpSenderBase.java:774) ~[ibis-adapterframework-core-7.9-20221027.201216.jar:7.9-20221027.201216]
	at nl.nn.adapterframework.http.HttpSenderBase.sendMessage(HttpSenderBase.java:653) ~[ibis-adapterframework-core-7.9-20221027.201216.jar:7.9-20221027.201216]
	at nl.nn.adapterframework.http.HttpSenderBase$$FastClassBySpringCGLIB$$f73d91f3.invoke(<generated>) ~[?:?]
	... suppressed 19 lines
	at nl.nn.adapterframework.http.HttpSender$$EnhancerBySpringCGLIB$$38e7f03b.sendMessage(<generated>) ~[?:?]
	at nl.nn.adapterframework.senders.ParallelSenderExecutor.run(ParallelSenderExecutor.java:57) ~[ibis-adapterframework-core-7.9-20221027.201216.jar:7.9-20221027.201216]
	... 
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:316) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.13.jar:4.5.13]
	at nl.nn.adapterframework.http.HttpSenderBase.sendMessageAndProvideForwardName(HttpSenderBase.java:746) ~[ibis-adapterframework-core-7.9-20221027.201216.jar:7.9-20221027.201216]
	... 25 more`

**Comment by ricardovh** [comment]
Related to #3579

**Comment by gvanbrakel** [comment]
I can imagine this is caused by the fact that the results of the enclosing sender is constructed from the results of the child senders only after all senders have finished. This keeps the connection of each sender open until all senders have finished
