### ISSUE TITLE
NPE on cleanup Database job

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3965]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When running the cleanup Database job, I get an NPE:
```
2022-11-08 10:45:54,696 ERROR [cleanup Database[IbisScheduler_Worker-4]] null scheduler.ConfiguredJob - JobExecutionException while running Job [cleanup Database]
java.lang.NullPointerException
      at nl.nn.adapterframework.configuration.Configuration.getScheduledJobs(Configuration.java:521) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.scheduler.job.CleanupDatabaseJob.getAllLockerDatasourceNames(CleanupDatabaseJob.java:198) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.scheduler.job.CleanupDatabaseJob.beforeExecuteJob(CleanupDatabaseJob.java:103) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.scheduler.JobDef.executeJob(JobDef.java:366) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.scheduler.ConfiguredJob.execute(ConfiguredJob.java:62) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
      at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:?]
```

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7.3
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Lijkt er op dat de IbisManager niet gevonden kan worden? 
https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/scheduler/job/CleanupDatabaseJob.java#L198
Heel apart..

**Comment by ricardovh** [comment]
> Lijkt er op dat de IbisManager niet gevonden kan worden? https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/scheduler/job/CleanupDatabaseJob.java#L198 Heel apart..

Let op, in 7.7.3 waar ik dit issue waarneem is die op regel 198 al een stapje verder in de logica en daar kan die alleen komen als die de ibisManager wel kan vinden: https://github.com/ibissource/iaf/blob/v7.7.3/core/src/main/java/nl/nn/adapterframework/scheduler/job/CleanupDatabaseJob.java#L198

**Comment by nielsm5** [comment]
In `Configuration.getScheduleManager` moet een dergelijke check komen die ook in `Configuration.getRegisteredAdapter` zit.
