### ISSUE TITLE
ErrorMessage details not displayed trying to browse message

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#3979]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When analyzing #3976 it appeared to me that the errormessage details are not shown on screen, where the are expected. The error is seen in the logging

**Reporter**
Gerrit

**To Reproduce**
1. Go to iaf-test
2. Run the MessageStoreSenderAndListenerPeek scenarios once
3. Browse the 'Done' status of the MessageStoreListener
4. See error related to #3976 appear, without details

**Screenshots**
![image](https://user-images.githubusercontent.com/4170104/201070984-f66ffb60-af51-4543-a295-d78f14e7cf74.png)

**Environment**
```
FF! 7.9-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_312-b07)
Heap size: 380M, total JVM memory: 524M
Free disk space: 87GB, total disk space: 476GB
Up since: 2022-11-10 11:10:37 (36m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by ricardovh** [comment]
Also in 7.7.3:
 ```2022-11-10 12:39:12,584 WARN [WebContainer : 7] null api.ApiException - cannot deserialize message: could not extract message: (StreamCorruptedException) invalid stream header: 3C726573
nl.nn.adapterframework.core.ListenerException: cannot deserialize message: could not extract message: (StreamCorruptedException) invalid stream header: 3C726573
      at nl.nn.adapterframework.jdbc.JdbcMessageBrowser.browseMessage(JdbcMessageBrowser.java:387) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.getMessageText(TransactionalStorage.java:623) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.getMessage(TransactionalStorage.java:617) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.browseMessage(TransactionalStorage.java:122) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[?:1.8.0]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
      at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
      at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.4.4.jar:3.4.4]
      at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.4.4.jar:3.4.4]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[cxf-rt-frontend-jaxrs-3.4.4.jar:3.4.4]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[cxf-rt-frontend-jaxrs-3.4.4.jar:3.4.4]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.4.4.jar:3.4.4]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.4.4.jar:3.4.4]
      at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[cxf-core-3.4.4.jar:3.4.4]
      at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.4.4.jar:3.4.4]
      at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at nl.nn.adapterframework.webcontrol.api.ServletDispatcher.invoke(ServletDispatcher.java:150) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.j2ee.servlet.jar:?]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273) ~[cxf-rt-transports-http-3.4.4.jar:3.4.4]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:143) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:96) ~[com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
      at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.17.2.jar:2.17.2]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4238) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebAppImpl.handleRequest(WebAppImpl.java:2210) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1033) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909) ~[com.ibm.ws.runtime.jar:?]
Caused by: nl.nn.adapterframework.jdbc.JdbcException: could not extract message: (StreamCorruptedException) invalid stream header: 3C726573
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:834) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:145) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.jdbc.JdbcMessageBrowser.browseMessage(JdbcMessageBrowser.java:381) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
       ... 61 more
Caused by: java.io.StreamCorruptedException: invalid stream header: 3C726573
      at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:1111) ~[?:1.8.0]
      at java.io.ObjectInputStream.<init>(ObjectInputStream.java:451) ~[?:1.8.0]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:809) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage.retrieveObject(JdbcTransactionalStorage.java:824) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
       ... 63 more```
