### ISSUE TITLE
Missing FilePermission on tivoli/tam/PolicyDirector/ 

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#4180]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We see in the systemout.log a lot of warnings:
000001a8 SecurityManag W   SECJ0314W: Current Java 2 Security policy reported a potential violation of Java 2 Security Permission. Refer to the InfoCenter for further information.
Permission:
/xxx/xxx/tivoli/tam/PolicyDirector/ : Access denied ("java.io.FilePermission" "/xxx/xxx/tivoli/tam/PolicyDirector/" "read")
(xxx is replaced by me)

We added a FilePermission rule in the was.policy, but the same error keeps occurring.
In the stacktrace I see :
at nl.nn.adapterframework.extensions.cmis.mtom.MtomProxy.service(MtomProxy.java:64)

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**
systemout.log and was.policy send via mail

**Environment**
location send via mail

**Additional Environment**
FF 7.7.5

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)
```
[13-12-22 17:10:48:805 CET] 000001a8 SecurityManag W SECJ0314W: Current Java 2 Security policy reported a potential violation of Java 2 Security Permission. Refer to the InfoCenter for further information.

Permission:

/opt/WAS/tivoli/tam/PolicyDirector/ : Access denied ("java.io.FilePermission" "/opt/WAS/tivoli/tam/PolicyDirector/" "read")


Code:_nolog

Stack Trace:

java.security.AccessControlException: Access denied ("java.io.FilePermission" "/opt/WAS/tivoli/tam/PolicyDirector/" "read")
      at java.security.AccessController.throwACE(AccessController.java:176)
      at java.security.AccessController.checkPermissionHelper(AccessController.java:238)
      at java.security.AccessController.checkPermission(AccessController.java:385)
      at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
      at com.ibm.ws.security.core.SecurityManager.checkPermission(SecurityManager.java:208)
      at sun.misc.URLClassPath.check(URLClassPath.java:743)
      at sun.misc.URLClassPath.checkURL(URLClassPath.java:723)
      at java.net.URLClassLoader.findResource(URLClassLoader.java:926)
      at java.lang.ClassLoader.getResource(ClassLoader.java:601)
      at java.lang.ClassLoader.getResource(ClassLoader.java:598)
      at java.lang.ClassLoader.getSystemResource(ClassLoader.java:828)
      at org.apache.cxf.resource.ClasspathResolver.resolve(ClasspathResolver.java:38)
      at org.apache.cxf.resource.DefaultResourceManager.findResource(DefaultResourceManager.java:118)
      at org.apache.cxf.resource.DefaultResourceManager.resolveResource(DefaultResourceManager.java:58)
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:199)
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
      at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
      at org.apache.chemistry.opencmis.server.impl.webservices.CmisWebServicesServlet.handleRequest(CmisWebServicesServlet.java:182)
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
      at nl.nn.adapterframework.extensions.cmis.mtom.MtomProxy.service(MtomProxy.java:64)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235)
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779)
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478)
      at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179)
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:143)
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:96)
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226)
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
      at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979)
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119)
      at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4238)
      at com.ibm.ws.webcontainer.webapp.WebAppImpl.handleRequest(WebAppImpl.java:2210)
      at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
      at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1033)
      at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
      at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
      at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
      at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)
      at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
      at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
      at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
      at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
      at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
      at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
      at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)

```

**Comment by nielsm5** [comment]
I find it a bit strange that a web endpoint is looking into the TAM directory. From what I can see in the stacktrace, the framework isn't actually involved yet. Could you elaborate as to what is exactly going on here?
If it is 'just' file permission issue, I do not think we can help you out here. It's not a framework related action that is performed.

**Comment by rvdstel** [comment]
We have found the issue. The last hyphen in the rule we had added should not be there : 
**not working:**
permission java.io.FilePermission "${was.install.root}${/}tivoli${/}tam${/}PolicyDirector${/}-", "read";
**working:**
permission java.io.FilePermission "${was.install.root}${/}tivoli${/}tam${/}PolicyDirector${/}", "read";
