### ISSUE TITLE
ActiveMQ ClassCastException in JBoss and WildFly

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#4304]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
While running iaf-test with ActiveMQ on JBoss and WildFly, a ClassCastException appears:
```
Unable to get managed connection for java:/jms/qcf-activemq: (ResourceException) Could not create connection.: (JMSException) Could not create Transport. Reason: (JMSException) Could not create Transport. Reason: (IOException) Transport scheme NOT recognized: [tcp]: () class org.apache.activemq.transport.tcp.TcpTransportFactory cannot be cast to class org.apache.activemq.transport.TransportFactory (org.apache.activemq.transport.tcp.TcpTransportFactory is in unnamed module of loader 'deployment.iaf-test.war' @1cc9a018; org.apache.activemq.transport.TransportFactory is in unnamed module of loader 'deployment.activemq-rar.rar' @57732339)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.MessagingSource.createSession(MessagingSource.java:257)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.JMSFacade.createSession(JMSFacade.java:243)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.JmsQueueBrowserIterator.<init>(JmsQueueBrowserIterator.java:48)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.JmsMessageBrowser.getIterator(JmsMessageBrowser.java:69)
	... 132 more
Caused by: javax.jms.JMSException: IJ000453: Unable to get managed connection for java:/jms/qcf-activemq
	at deployment.activemq-rar.rar//org.apache.activemq.ra.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:102)
	at deployment.activemq-rar.rar//org.apache.activemq.ra.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:67)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.JmsMessagingSourceFactory$ConnectionFactoryWrapper.createConnection(JmsMessagingSourceFactory.java:150)
	at deployment.iaf-test.war//org.springframework.jms.connection.TransactionAwareConnectionFactoryProxy.createConnection(TransactionAwareConnectionFactoryProxy.java:153)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.MessagingSource.createConnection(MessagingSource.java:213)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.MessagingSource.createAndStartConnection(MessagingSource.java:220)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.MessagingSource.getConnection(MessagingSource.java:228)
	at deployment.iaf-test.war//nl.nn.adapterframework.jms.MessagingSource.createSession(MessagingSource.java:255)
	... 135 more

```

**Reporter**
Gerrit

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
7.9 snapshot
```

**Comment by nielsm5** [comment]
runtime dependencies in iaf-test module naar los profiel, standaard aan op eclipse.

**Comment by gvanbrakel** [comment]
Problem is still present:
(ClassCastException) class org.apache.activemq.transport.tcp.TcpTransportFactory cannot be cast to class org.apache.activemq.transport.TransportFactory (org.apache.activemq.transport.tcp.TcpTransportFactory is in unnamed module of loader 'deployment.iaf-test.war' @f946e44; org.apache.activemq.transport.TransportFactory is in unnamed module of loader 'deployment.activemq-rar.rar' @4084faec)

**Comment by VBPham** [comment]
CI probably used old image. As with "?jms.xaAckMode=1" in the connection string for these two appservers the jms adapter wouldn't even start up as was mentioned in this PR #3690. Local testing was succesful. The approach now will be to remove the parameter en hope that coming Saturday a new image will be build and tested
