### ISSUE TITLE
ExchangeMailListener could not extract ReceivedBy address

### ISSUE THREAD

**Issue by Bibi0803** [ibissource/iaf#4328]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The adapter which uses ExchangeMailListener gives an error "Could not extract ReceivedBy address"

**Reporter**
Bibi

**Log message**
```2023-01-11 14:39:49,772 ERROR [ListenTask[Receiver [HandleEmail]]-273167] {} receivers.Receiver - Receiver [HandleEmail] error occured
nl.nn.adapterframework.core.ListenerException: Cannot change processState to [AVAILABLE] for [AAMkADg1ZjU0M2EwLWI3NWItNGFjMC05N2ZhLWJlNGNmZjVhNjgyMgBGAAAAAACgHl/XCcHwTLx9wzuuz76qBwDJERnQ/mD8R50sQsHGTaqQAABlFXZ5AADJERnQ/mD8R50sQsHGTaqQAAC69ECOAAA=]: Could not extract ReceivedBy address: (ServiceRequestException) The request failed. : (IllegalStateException) Connection manager has been shut down
      at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:398) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.receivers.PullingListenerContainer$ListenTask.rollBack(PullingListenerContainer.java:385) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.receivers.PullingListenerContainer$ListenTask.run(PullingListenerContainer.java:343) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at java.lang.Thread.run(Thread.java:826) ~[?:2.9 (08-17-2022)]
Caused by: nl.nn.adapterframework.filesystem.FileSystemException: Could not extract ReceivedBy address: (ServiceRequestException) The request failed. : (IllegalStateException) Connection manager has been shut down
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:498) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:129) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:375) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      ... 3 more
Caused by: nl.nn.adapterframework.filesystem.FileSystemException: Could not extract ReceivedBy address: (ServiceRequestException) The request failed. : (IllegalStateException) Connection manager has been shut down
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.getReceivedBy(ExchangeFileSystem.java:975) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:486) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:129) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:375) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      ... 3 more
Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. Connection manager has been shut down
      at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.ExchangeService.internalLoadPropertiesForItems(ExchangeService.java:1324) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.service.item.Item.internalLoad(Item.java:193) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.service.ServiceObject.load(ServiceObject.java:372) ~[ews-java-api-2.0.jar:?]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.getReceivedBy(ExchangeFileSystem.java:956) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:486) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:129) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:375) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      ... 3 more
Caused by: java.lang.IllegalStateException: Connection manager has been shut down
      at org.apache.http.util.Asserts.check(Asserts.java:34) ~[httpcore-4.4.16.jar:4.4.16]
      at org.apache.http.impl.conn.BasicHttpClientConnectionManager.getConnection(BasicHttpClientConnectionManager.java:235) ~[httpclient-4.5.14.jar:4.5.14]
      at org.apache.http.impl.conn.BasicHttpClientConnectionManager$1.get(BasicHttpClientConnectionManager.java:204) ~[httpclient-4.5.14.jar:4.5.14]
      at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) ~[httpclient-4.5.14.jar:4.5.14]
      at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]
      at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]
      at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]
      at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]
      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.14.jar:4.5.14]
      at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:292) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:720) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.ExchangeService.internalLoadPropertiesForItems(ExchangeService.java:1324) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.service.item.Item.internalLoad(Item.java:193) ~[ews-java-api-2.0.jar:?]
      at microsoft.exchange.webservices.data.core.service.ServiceObject.load(ServiceObject.java:372) ~[ews-java-api-2.0.jar:?]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.getReceivedBy(ExchangeFileSystem.java:956) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:486) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:129) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:375) ~[ibis-adapterframework-core-7.8-RC3-20230104.175834.jar:7.8-RC3-20230104.175834]
      ... 3 more
```

**Configuration**
```
<receiver 
			name="HandleEmail" pollInterval="${handleEmail.pollInterval}">
			<listener 
				className="nl.nn.adapterframework.receivers.ExchangeMailListener"
				name="HandleEmail" 
				inputFolder="${handleEmail.inputFolder}"
				inProcessFolder="${handleEmail.tempFolder}" 
				processedFolder="${handleEmail.outputFolder}"
				mailAddress="${handleEmail.mailAddress}" 
				url="${handleEmail.url}"
				authAlias="${handleEmail.authAlias}" 
				messageType="mime"
				proxyAuthAlias="${handleEmail.proxyAuthAlias}"
				proxyHost="${handleEmail.proxyHost}" 
				proxyPort="${handleEmail.proxyPort}" 
				delete="true"
				tenantId="${handleEmail.tenantId}"
				verifyHostname="false"
				allowSelfSignedCertificates="true"
				disableMessageBrowsers="true"
				clientSecret="${handleEmail.clientSecret}"
				clientId="${handleEmail.clientId}"
			/>
		</receiver>
```

**Environment**
```
FF! 7.8-RC3-20230104.175834: Ibis4Scan
Running on LPZWNL000039597 using Apache Tomcat/9.0.68
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 307M, total JVM memory: 647M
Free disk space: 150GB, total disk space: 237GB
Up since: 2023-01-11 15:46:26 (3m) 
```

**Comment by Bibi0803** [comment]
[ibis4scan.log](https://github.com/ibissource/iaf/files/10464796/ibis4scan.log)
[ibis4scan_1.log](https://github.com/ibissource/iaf/files/10465085/ibis4scan_1.log)
I have tried to restart the adapter and put an email in the inbox folder of the email box to recreate the situation, attached are the log files, starting time of the adapter is 2023-01-20 10:02:01,326, hope it helps.

**Comment by tnleeuw** [comment]
@Bibi0803 Thank you, I will analyse the logs and I will get back to you!

**Comment by tnleeuw** [comment]
@Bibi0803 In de laatste 7.8 snapshot builds is extra logging toegevoegd waarmee we hopelijk beter inzicht kunnen krijgen in wat er gebeurd en wat er fout gaat.
Als je deze zou kunnen gebruiken voor een test?

**Comment by tnleeuw** [comment]
From logging done by the latest snapshot, I see an exception that was previously suppressed. This exception says that for an operation done, you do not have permission, and so an HTTP error 403 is returned from the Exchange web service.

```
2023-01-25 15:48:36,630 ERROR [ListenTask[Receiver [HandleEmail]]-173] {} receivers.Receiver - Receiver [HandleEmail] error occured
nl.nn.adapterframework.core.ListenerException: Cannot change processState to [INPROCESS] for [...]: (ServiceRequestException) The request failed. : (ServiceRequestException) The request failed. : (HttpErrorException) The remote server returned an error: (403)
	at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:407) ~[ibis-adapterframework-core-7.8-RC3-20230124.114439.jar:7.8-RC3-20230124.114439]
	at nl.nn.adapterframework.receivers.PullingListenerContainer$ListenTask.run(PullingListenerContainer.java:266) ~[ibis-adapterframework-core-7.8-RC3-20230124.114439.jar:7.8-RC3-20230124.114439]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]
Caused by: nl.nn.adapterframework.filesystem.FileSystemException: (ServiceRequestException) The request failed. : (ServiceRequestException) The request failed. : (HttpErrorException) The remote server returned an error: (403)
	at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:508) ~[ibis-adapterframework-core-7.8-RC3-20230124.114439.jar:7.8-RC3-20230124.114439]
	at nl.nn.adapterframework.filesystem.ExchangeFileSystem.exists(ExchangeFileSystem.java:127) ~[ibis-adapterframework-core-7.8-RC3-20230124.114439.jar:7.8-RC3-20230124.114439]
	at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:384) ~[ibis-adapterframework-core-7.8-RC3-20230124.114439.jar:7.8-RC3-20230124.114439]
	... 2 more
Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. The request failed. The remote server returned an error: (403)
...
```

**Comment by VBPham** [comment]
Bibi has tested and confirmed that dragging mails works again
