### ISSUE TITLE
Named query parameters do not work inside ForEachChildElementPipe

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#440]
Kay discovered a case where named query parameters do not work. The following insert statement fails: "INSERT INTO visit VALUES(?{bookingId}, ?{seq}, ?{hostId}, ?{productId}, ?{startDate}, ?{endDate}, ?{price})" with a syntax error while the following insert statement succeeds: "INSERT INTO visit VALUES(?, ?, ?, ?, ?, ?, ?)".

**Category**
 - Frank Framework

**To Reproduce**
1. Clone the Frank!Manual GitHub repository.
2. Clone Frank!Runner.
3. Open the build.xml file within the Frank!Runner.
4. Edit property ff.version to be 7.5-RC1
5. Edit build.properties. It should have the line "project.dir=frank-manual/src/gettingStarted" if your frank-manual and frank-runner checkouts have the same root directory.
6. In the Frank!Manual repository, checkout SHA 75113d0d0eb10172e6ecabb6d4430f4952c2b5ba.
7. Find and open file ConfigurationIngestBooking.xml. The query under discussion is at line 53. Replace it by the query mentioned earlier that has named parameters.
8. Start the Frank!Runner.
9. In the Test Pipeline screen, run the IngestBooking adapter and provide the following XML:

<booking id="1">
  <travelerId>2</travelerId>
  <price>500.00</price>
  <fee>100.00</fee>
  <destination hostId="3" productId="4">
    <price>400.00</price>
    <startDate>2018-12-27</startDate>
    <endDate>2019-01-02</endDate>
  </destination>
</booking>

**Expected behavior**
The adapter succeeds.

**Screenshots**
The adapter fails with the following exception:

<errorMessage timestamp="Thu Feb 20 11:38:31 CET 2020" originator="IAF 7.5-RC1" message="error during pipeline processing: Pipe [iterateDestinations] msgId [testmessage0a000096--143075e0_170622c4153_-7ffe] caught exception: Could not process list of elements using xpath [/destinations/destination]: (RuntimeException) nl.nn.adapterframework.xml.SaxException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [insertVisitSender] cannot getQueryExecutionContext: (JdbcSQLSyntaxErrorException) SQLState [42000], errorCode [42000]: Syntax error in SQL statement &quot;INSERT INTO visit VALUES(?{bookingId}, ?{seq}, ?{hostId}, ?{productId}, ?{startDate}, ?{endDate}, ?{price})[*]&quot; [42000-200]">

  <location class="nl.nn.adapterframework.pipes.ForEachChildElementPipe" name="iterateDestinations" />

  <details>nl.nn.adapterframework.core.ListenerException: Pipe [iterateDestinations] msgId [testmessage0a000096--143075e0_170622c4153_-7ffe] caught exception: Could not process list of elements using xpath [/destinations/destination]: (RuntimeException) nl.nn.adapterframework.xml.SaxException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [insertVisitSender] cannot getQueryExecutionContext: (JdbcSQLSyntaxErrorException) SQLState [42000], errorCode [42000]: Syntax error in SQL statement "INSERT INTO visit VALUES(?{bookingId}, ?{seq}, ?{hostId}, ?{productId}, ?{startDate}, ?{endDate}, ?{price})[*]" [42000-200]&#xD;

	at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:677)&#xD;

	at nl.nn.adapterframework.core.Adapter.processMessage(Adapter.java:557)&#xD;

	at nl.nn.adapterframework.webcontrol.api.TestPipeline.processMessage(TestPipeline.java:211)&#xD;

	at nl.nn.adapterframework.webcontrol.api.TestPipeline.postTestPipeLine(TestPipeline.java:139)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#xD;

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;

	at java.lang.reflect.Method.invoke(Method.java:498)&#xD;

	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)&#xD;

	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)&#xD;

	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)&#xD;

	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)&#xD;

	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:377)&#xD;

	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:200)&#xD;

	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)&#xD;

	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)&#xD;

	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)&#xD;

	at nl.nn.adapterframework.webcontrol.api.ServletDispatcher.service(ServletDispatcher.java:150)&#xD;

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)&#xD;

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)&#xD;

	at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)&#xD;

	at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)&#xD;

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)&#xD;

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)&#xD;

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)&#xD;

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)&#xD;

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)&#xD;

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)&#xD;

	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)&#xD;

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)&#xD;

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)&#xD;

	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1195)&#xD;

	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)&#xD;

	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:319)&#xD;

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)&#xD;

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)&#xD;

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)&#xD;

	at java.lang.Thread.run(Thread.java:748)&#xD;

Caused by: nl.nn.adapterframework.core.PipeRunException: Pipe [iterateDestinations] msgId [testmessage0a000096--143075e0_170622c4153_-7ffe] caught exception: Could not process list of elements using xpath [/destinations/destination]: (RuntimeException) nl.nn.adapterframework.xml.SaxException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [insertVisitSender] cannot getQueryExecutionContext: (JdbcSQLSyntaxErrorException) SQLState [42000], errorCode [42000]: Syntax error in SQL statement "INSERT INTO visit VALUES(?{bookingId}, ?{seq}, ?{hostId}, ?{productId}, ?{startDate}, ?{endDate}, ?{price})[*]" [42000-200]&#xD;

	at nl.nn.adapterframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:754)&#xD;

	at nl.nn.adapterframework.pipes.MessageSendingPipe$$FastClassBySpringCGLIB$$b131b2cb.invoke(&lt;generated&gt;)&#xD;

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)&#xD;

	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)&#xD;

	at nl.nn.adapterframework.pipes.ForEachChildElementPipe$$EnhancerBySpringCGLIB$$3bdc129d.doPipe(&lt;generated&gt;)&#xD;

	at nl.nn.adapterframework.stream.StreamingPipe.doPipe(StreamingPipe.java:80)&#xD;

	at nl.nn.adapterframework.processors.CorePipeProcessor.processPipe(CorePipeProcessor.java:30)&#xD;

	at nl.nn.adapterframework.processors.CheckMessageSizePipeProcessor.processPipe(CheckMessageSizePipeProcessor.java:37)&#xD;

	at nl.nn.adapterframework.processors.LockerPipeProcessor.processPipe(LockerPipeProcessor.java:58)&#xD;

	at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.processPipe(TransactionAttributePipeProcessor.java:61)&#xD;

	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:57)&#xD;

	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$FastClassBySpringCGLIB$$3159a29c.invoke(&lt;generated&gt;)&#xD;

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)&#xD;

	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:96)&#xD;

	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:133)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#xD;

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;

	at java.lang.reflect.Method.invoke(Method.java:498)&#xD;

	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)&#xD;

	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)&#xD;

	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)&#xD;

	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)&#xD;

	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$EnhancerBySpringCGLIB$$3244c027.processPipe(&lt;generated&gt;)&#xD;

	at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:78)&#xD;

	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$FastClassBySpringCGLIB$$feb9be85.invoke(&lt;generated&gt;)&#xD;

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)&#xD;

	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:96)&#xD;

	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:106)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#xD;

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;

	at java.lang.reflect.Method.invoke(Method.java:498)&#xD;

	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)&#xD;

	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)&#xD;

	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)&#xD;

	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)&#xD;

	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$365d4d82.processPipe(&lt;generated&gt;)&#xD;

	at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:78)&#xD;

	at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:162)&#xD;

	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(&lt;generated&gt;)&#xD;

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)&#xD;

	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:96)&#xD;

	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:88)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#xD;

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;

	at java.lang.reflect.Method.invoke(Method.java:498)&#xD;

	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)&#xD;

	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)&#xD;

	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)&#xD;

	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)&#xD;

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)&#xD;

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)&#xD;

	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$1910e3a2.processPipeLine(&lt;generated&gt;)&#xD;

	at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:68)&#xD;

	at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:49)&#xD;

	at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:35)&#xD;

	at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:48)&#xD;

	at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:539)&#xD;

	at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:657)&#xD;

	... 44 more&#xD;

Caused by: nl.nn.adapterframework.core.SenderException: Could not process list of elements using xpath [/destinations/destination]: (RuntimeException) nl.nn.adapterframework.xml.SaxException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [insertVisitSender] cannot getQueryExecutionContext: (JdbcSQLSyntaxErrorException) SQLState [42000], errorCode [42000]: Syntax error in SQL statement "INSERT INTO visit VALUES(?{bookingId}, ?{seq}, ?{hostId}, ?{productId}, ?{startDate}, ?{endDate}, ?{price})[*]" [42000-200]&#xD;

	at nl.nn.adapterframework.pipes.ForEachChildElementPipe.iterateOverInput(ForEachChildElementPipe.java:366)&#xD;

	at nl.nn.adapterframework.pipes.IteratingPipe.sendMessage(IteratingPipe.java:382)&#xD;

	at nl.nn.adapterframework.pipes.ForEachChildElementPipe.sendMessage(ForEachChildElementPipe.java:148)&#xD;

	at nl.nn.adapterframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:581)&#xD;

	... 121 more&#xD;

Caused by: java.lang.RuntimeException: nl.nn.adapterframework.xml.SaxException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [insertVisitSender] cannot getQueryExecutionContext: (JdbcSQLSyntaxErrorException) SQLState [42000], errorCode [42000]: Syntax error in SQL statement "INSERT INTO visit VALUES(?{bookingId}, ?{seq}, ?{hostId}, ?{productId}, ?{startDate}, ?{endDate}, ?{price})[*]" [42000-200]&#xD;

	at org.apache.xalan.transformer.TransformerImpl.run(TransformerImpl.java:3484)&#xD;

	at org.apache.xalan.transformer.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:408)&#xD;

	at org.xml.sax.helpers.XMLFilterImpl.endDocument(XMLFilterImpl.java:497)&#xD;

	at org.xml.sax.helpers.XMLFilterImpl.endDocument(XMLFilterImpl.java:497)&#xD;

	at org.apache.xerces.parsers.AbstractSAXParser.endDocument(Unknown Source)&#xD;

	at org.apache.xerces.impl.XMLDocumentScannerImpl.endEntity(Unknown Source)&#xD;

	at org.apache.xerces.impl.XMLEntityManager.endEntity(Unknown Source)&#xD;

	at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)&#xD;

	at org.apache.xerces.impl.XMLEntityScanner.skipSpaces(Unknown Source)&#xD;

	at org.apache.xerces.impl.XMLDocumentScannerImpl$TrailingMiscDispatcher.dispatch(Unknown Source)&#xD;

	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)&#xD;

	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)&#xD;

	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)&#xD;

	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)&#xD;

	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)&#xD;

	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)&#xD;

	at nl.nn.adapterframework.util.XmlUtils.parseXml(XmlUtils.java:526)&#xD;

	at nl.nn.adapterframework.pipes.ForEachChildElementPipe.iterateOverInput(ForEachChildElementPipe.java:360)&#xD;

	... 124 more</details>

  <originalMessage messageId="testmessage0a000096--143075e0_170622c4153_-7ffe" receivedTime="Thu Feb 20 11:38:31 CET 2020">&lt;booking id="1"&gt;&#xD;

  &lt;travelerId&gt;2&lt;/travelerId&gt;&#xD;

  &lt;price&gt;500.00&lt;/price&gt;&#xD;

  &lt;fee&gt;100.00&lt;/fee&gt;&#xD;

  &lt;destination hostId="3" productId="4"&gt;&#xD;

    &lt;price&gt;400.00&lt;/price&gt;&#xD;

    &lt;startDate&gt;2018-12-27&lt;/startDate&gt;&#xD;

    &lt;endDate&gt;2019-01-02&lt;/endDate&gt;&#xD;

  &lt;/destination&gt;&#xD;

&lt;/booking&gt;</originalMessage>

</errorMessage>

**Environment:**
 - Application server: Tomcat, executed through the Frank!Runner.
 - Browser: Firefox
 - IAF Version: 7.5-RC1

**Comment by mhdirkse** [comment]
The Frank config was not right. The sender around the query did not have attribute useNamedParams="true".

**Comment by mhdirkse** [comment]
I added the useNamedParams line and checked that my adapter worked.
