### ISSUE TITLE
Error in Frank!Console: unable to convert response to JSON

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#4576]
**Describe the issue**
When you (re)load the Frank!Console an error message is displayed in the top right corner saying "unable to convert response to JSON"

**Reporter**
Jaco de Groot

**To Reproduce**
1. Clone https://github.com/ibissource/zaakbrug
2. Start ZaakBrug with the Frank!Runner
3. Go to the Frank!Console

**Screenshots**

![image](https://user-images.githubusercontent.com/2970084/221843339-2ed08b4c-84ff-41e6-8a61-e32c59659434.png)

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 7.9-20230224.143242: ZaakBrug
Running on xxx using Apache Tomcat/9.0.68
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 652M, total JVM memory: 765M
Free disk space: 48GB, total disk space: 475GB
Up since: 2023-02-28 12:04:29 (35m) 
```

**Additional Environment**
 - Firefox

**Additional Context**
The logfile showes:
```
2023-02-28 12:38:46,929 ERROR [http-nio-80-exec-3] {} bus.BusException - unable to convert response to JSON
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.HashMap["Translate"]->java.util.HashMap["warnings"]->java.util.Collections$UnmodifiableList[6087])
      at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:153) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624) ~[jackson-databind-2.14.2.jar:2.14.2]
      at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3869) ~[jackson-databind-2.14.2.jar:2.14.2]
      at nl.nn.adapterframework.management.bus.ResponseMessage$Builder.toJson(ResponseMessage.java:95) ~[ibis-adapterframework-core-7.9-20230224.143242.jar:7.9-20230224.143242]
      at nl.nn.adapterframework.management.bus.ResponseMessage$Builder.toJson(ResponseMessage.java:86) ~[ibis-adapterframework-core-7.9-20230224.143242.jar:7.9-20230224.143242]
      at nl.nn.adapterframework.management.bus.ResponseMessage.ok(ResponseMessage.java:128) ~[ibis-adapterframework-core-7.9-20230224.143242.jar:7.9-20230224.143242]
      at nl.nn.adapterframework.management.bus.endpoints.ServerStatistics.getApplicationWarnings(ServerStatistics.java:180) ~[ibis-adapterframework-core-7.9-20230224.143242.jar:7.9-20230224.143242]
      ... suppressed 4 lines
      at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.25.jar:5.3.25]
      ... suppressed 9 lines
      at org.springframework.messaging.MessageChannel.send(MessageChannel.java:45) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.25.jar:5.3.25]
      ... suppressed 8 lines
      at org.springframework.integration.dispatcher.BroadcastingDispatcher.invokeHandler(BroadcastingDispatcher.java:222) ~[spring-integration-core-5.5.16.jar:5.5.16]
      at org.springframework.integration.dispatcher.BroadcastingDispatcher.dispatch(BroadcastingDispatcher.java:178) ~[spring-integration-core-5.5.16.jar:5.5.16]
      at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.16.jar:5.5.16]
      at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.16.jar:5.5.16]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:233) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.messaging.core.AbstractMessagingTemplate.sendAndReceive(AbstractMessagingTemplate.java:46) ~[spring-messaging-5.3.25.jar:5.3.25]
      at org.springframework.integration.core.MessagingTemplate.sendAndReceive(MessagingTemplate.java:97) ~[spring-integration-core-5.5.16.jar:5.5.16]
      at org.springframework.integration.gateway.MessagingGatewaySupport.doSendAndReceive(MessagingGatewaySupport.java:522) ~[spring-integration-core-5.5.16.jar:5.5.16]
      at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceiveMessage(MessagingGatewaySupport.java:492) ~[spring-integration-core-5.5.16.jar:5.5.16]
      at nl.nn.adapterframework.lifecycle.Gateway.sendSyncMessage(Gateway.java:30) ~[ibis-adapterframework-core-7.9-20230224.143242.jar:7.9-20230224.143242]
      at nl.nn.adapterframework.management.web.FrankApiBase.sendSyncMessage(FrankApiBase.java:86) ~[ibis-adapterframework-console-7.9-20230224.143242.jar:7.9-20230224.143242]
      at nl.nn.adapterframework.management.web.FrankApiBase.callSyncGateway(FrankApiBase.java:104) ~[ibis-adapterframework-console-7.9-20230224.143242.jar:7.9-20230224.143242]
      at nl.nn.adapterframework.management.web.ServerStatistics.getServerConfiguration(ServerStatistics.java:62) ~[ibis-adapterframework-console-7.9-20230224.143242.jar:7.9-20230224.143242]
      ... suppressed 4 lines
      at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.5.5.jar:3.5.5]
      at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.5.5.jar:3.5.5]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[cxf-rt-frontend-jaxrs-3.5.5.jar:3.5.5]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[cxf-rt-frontend-jaxrs-3.5.5.jar:3.5.5]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.5.5.jar:3.5.5]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.5.5.jar:3.5.5]
      at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[cxf-core-3.5.5.jar:3.5.5]
      at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.5.5.jar:3.5.5]
      at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at nl.nn.adapterframework.management.web.ServletDispatcher.invoke(ServletDispatcher.java:149) ~[ibis-adapterframework-console-7.9-20230224.143242.jar:7.9-20230224.143242]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[servlet-api.jar:4.0.FR]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[cxf-rt-transports-http-3.5.5.jar:3.5.5]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.68]
      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.68]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.68]
      ... suppressed 15 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar:5.3.25]
      ... suppressed 5 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar:5.3.25]
      ... suppressed 2 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar:5.3.25]
      ... suppressed 3 lines
      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.25.jar:5.3.25]
      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.25.jar:5.3.25]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.68]
      at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) ~[ibis-adapterframework-core-7.9-20230224.143242.jar:7.9-20230224.143242]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.68]
      at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.19.0.jar:2.19.0]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.68]
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:9.0.68]
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.68]
      at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[catalina.jar:9.0.68]
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.68]
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[catalina.jar:9.0.68]
      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-coyote.jar:9.0.68]
      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.68]
      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-coyote.jar:9.0.68]
      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-coyote.jar:9.0.68]
      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.68]
      at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.68]
      at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.68]
      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.68]
      at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]
Caused by: java.lang.NullPointerException
```

**Comment by nielsm5** [comment]
Is this consistent? The stacktrace isn't very helpful unfortunately. I've changed the mapping strategy last week, if this is/was a consistent problem, is it possible to try it again with the latest version?
