### ISSUE TITLE
WsdlXmlValidator throws NPE when a schema is imported to wsdl and referenced in other schema

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4995]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I use a WsdlXmlValidator. The wsdl that is configured in the validator imports a schema to the wsdl. The imported schema is referenced in other schema that is defined in wsdl:types section using the namespace. The wsdl seems to be valid by xmlspy. However, the framework throws NPE (see stacktrace below).

When the import is removed from wsdl but added in the specific schema it works. I would expect importing the schema to the wsdl  to work as well.

Original scenario:
```
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:import namespace="asd" location="xsd"/>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="asd"/>
		</xsd:schema>
	</wsdl:types>
</wsdl:definitions>
```

Workaround:
```
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="asd" schemaLocation="xsd"/>
		</xsd:schema>
	</wsdl:types>	
</wsdl:definitions>
```

```
2023-06-13 14:51:18,493 DEBUG [starting Adapter CreateImmediateDocument] {} validation.IntraGrammarPoolEntityResolver - resolveEntity publicId [null] baseSystemId [http://nn.be/XSD/BE/BE_EngageOne_UND/1/DeliverDocument/1] expandedSystemId [null] literalSystemId [null] namespace [http://nn-group.com/XSD/Generic/MessageHeader/1]
2023-06-13 14:51:18,493 WARN  [starting Adapter CreateImmediateDocument] {} validation.IntraGrammarPoolEntityResolver - namespace [http://nn-group.com/XSD/Generic/MessageHeader/1] not found in list of schemas
2023-06-13 14:51:18,493 ERROR [starting Adapter CreateImmediateDocument] {} core.Adapter - Adapter [CreateImmediateDocument] got error starting Adapter
org.apache.xerces.xni.XNIException: Cannot find resource [null] from systemId [null] with base [http://nn.be/XSD/BE/BE_EngageOne_UND/1/DeliverDocument/1]
	at nl.nn.adapterframework.validation.IntraGrammarPoolEntityResolver.resolveEntity(IntraGrammarPoolEntityResolver.java:90) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:2.12.2-xml-schema-1.1]
	at org.apache.xerces.impl.xs.XMLSchemaLoader.resolveDocument(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:?]
	at org.apache.xerces.impl.xs.traversers.XSDHandler.resolveSchema(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:?]
	at org.apache.xerces.impl.xs.traversers.XSDHandler.constructTrees(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:?]
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:?]
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:?]
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:?]
	at org.apache.xerces.parsers.XMLGrammarPreparser.preparseGrammar(Unknown Source) ~[ibis-xerces-2.12.2-xml-schema-1.1.jar:?]
	at nl.nn.adapterframework.validation.XercesXmlValidator.preparse(XercesXmlValidator.java:226) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at nl.nn.adapterframework.validation.XercesXmlValidator.preparse(XercesXmlValidator.java:212) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at nl.nn.adapterframework.validation.XercesXmlValidator.preparse(XercesXmlValidator.java:180) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at nl.nn.adapterframework.validation.XercesXmlValidator.start(XercesXmlValidator.java:155) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at nl.nn.adapterframework.pipes.XmlValidator.start(XmlValidator.java:191) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at nl.nn.adapterframework.pipes.MessageSendingPipe.start(MessageSendingPipe.java:868) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at nl.nn.adapterframework.pipes.MessageSendingPipe$$FastClassBySpringCGLIB$$b131b2cb.invoke(<generated>) ~[?:?]
	... suppressed 8 lines
	at nl.nn.adapterframework.pipes.SenderPipe$$EnhancerBySpringCGLIB$$3971d078.start(<generated>) ~[?:?]
	at nl.nn.adapterframework.core.PipeLine.start(PipeLine.java:544) ~[ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at nl.nn.adapterframework.core.Adapter$1.run(Adapter.java:813) [ibis-adapterframework-core-7.8.1-20230501.190146.jar:7.8.1-20230501.190146]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Reporter**
Ali

ff: 7.8.1-20230501.190146

**Comment by nielsm5** [comment]
I'm leaving this for now, you've got a workaround.
