### ISSUE TITLE
FixedQuerySender ZipException when reading a UUID type column from an H2 database

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#5462]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
From what I read about it, the issues seems to be specifically H2 returning the "wrong" type when retrieving the database schema. The type UUID is BINARY under the hood for H2. When retrieving the schema, H2 will return BINARY instead of UUID. Because of that I think the framework is trying to read it as a blob.

~~For most cases the workaround would be to simply change the column's type to something CHAR, but then you lose the ability to auto-generate UUID's in the database itself.~~

**Reporter**
MLenterman

**To Reproduce**
[BpelDatabaseChangelog.zip](https://github.com/ibissource/iaf/files/12730381/BpelDatabaseChangelog.zip)

**Screenshots**

**Configuration**
```xml
<SenderPipe name="InsertZgwZaakInformatieObjectSender">
                <FixedQuerySender
					name="InsertZgwZaakInformatieObjectFixedQuerySender"
                    query="INSERT INTO ENKELVOUDIGINFORMATIEOBJECT (DATA, FILE) VALUES (?{data}, ?{file})" 
                    queryType="OTHER"
                    />
                    <Param name="data" value="{&quot;count&quot;:123,&quot;next&quot;:&quot;http://api.example.org/accounts/?page=4&quot;,&quot;previous&quot;:&quot;http://api.example.org/accounts/?page=2&quot;,&quot;results&quot;:[{&quot;url&quot;:&quot;string&quot;,&quot;uuid&quot;:&quot;3fa85f64-5717-4562-b3fc-2c963f66afa6&quot;,&quot;zaak&quot;:&quot;string&quot;,&quot;resultaattype&quot;:&quot;string&quot;,&quot;toelichting&quot;:&quot;string&quot;}]}" />
					<Param name="file" value="=484SDF84WE94WEF1C1S3DC123SDC5SDC798WEC7" />
                <Forward name="success" path="SelectTopZgwZaakInformatieObjectSender" />
                <Forward name="exception" path="EXCEPTION" />
            </SenderPipe>

			<SenderPipe name="SelectTopZgwZaakInformatieObjectSender">
                <FixedQuerySender
					name="SelectTopZgwZaakInformatieObjectFixedQuerySender"
                    query="SELECT PK,ID,DATA,FILE FROM ENKELVOUDIGINFORMATIEOBJECT ORDER BY PK DESC LIMIT 1"
					queryType="SELECT"
                    />
                <Forward name="success" path="EXIT" />
                <Forward name="exception" path="EXCEPTION" />
            </SenderPipe>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20230905.223421: Openforms2bpel 1.0.0
Running on 584df509293f using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (11.0.20.1+1)
Heap size: 727M, total JVM memory: 1443M
Free disk space: 208GB, total disk space: 251GB
Up since: 2023-09-26 18:38:46 (54m) 
```

**Additional Environment**
 - DBMS: H2

**Additional Context**
```
2023-09-26 18:24:07,963 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create} stream.Message - returning String Message[4ee9e292:String] as InputSource
2023-09-26 18:24:07,966 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} jdbc.FixedQuerySender - [nl.nn.adapterframework.jdbc.FixedQuerySender] [SelectTopZgwZaakInformatieObjectFixedQuerySender] obtaining prepared statement to execute
2023-09-26 18:24:07,966 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} jdbc.FixedQuerySender - [nl.nn.adapterframework.jdbc.FixedQuerySender] [SelectTopZgwZaakInformatieObjectFixedQuerySender] preparing statement for query [SELECT PK,ID,DATA,FILE FROM ENKELVOUDIGINFORMATIEOBJECT ORDER BY PK DESC LIMIT 1]
2023-09-26 18:24:07,982 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} jdbc.FixedQuerySender - [nl.nn.adapterframework.jdbc.FixedQuerySender] [SelectTopZgwZaakInformatieObjectFixedQuerySender] obtained prepared statement to execute
2023-09-26 18:24:07,983 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} jdbc.FixedQuerySender - [nl.nn.adapterframework.jdbc.FixedQuerySender] [SelectTopZgwZaakInformatieObjectFixedQuerySender] executing a SELECT SQL command
2023-09-26 18:24:07,987 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} stream.MessageOutputStream - providing MessageOutputStreamCap for FixedQuerySender [SelectTopZgwZaakInformatieObjectFixedQuerySender]
2023-09-26 18:24:07,990 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} stream.MessageOutputStream - MessageOutputStream of FixedQuerySender [SelectTopZgwZaakInformatieObjectFixedQuerySender] returning native[<null>]
2023-09-26 18:24:07,990 DEBUG [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} stream.MessageOutputStream - MessageOutputStream of FixedQuerySender [SelectTopZgwZaakInformatieObjectFixedQuerySender] returning Writer as ContentHandler
2023-09-26 18:24:07,997 ERROR [http-nio-8080-exec-2] {adapter=enkelvoudiginformatieobject_create, pipe=SelectTopZgwZaakInformatieObjectSender} util.DB2XMLWriter - Error occured at row [0]
nl.nn.adapterframework.core.SenderException: error getting fieldvalue column [2] fieldType [BINARY]: (ZipException) incorrect header check
      at nl.nn.adapterframework.util.DB2XMLWriter.getRowXml(DB2XMLWriter.java:235) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:?]
      at nl.nn.adapterframework.util.DB2XMLWriter.getXML(DB2XMLWriter.java:138) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:?]
      at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.getResult(JdbcQuerySenderBase.java:528) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.executeSelectQuery(JdbcQuerySenderBase.java:704) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.executeSelectQuery(JdbcQuerySenderBase.java:689) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.executeStatementSet(JdbcQuerySenderBase.java:324) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.jdbc.FixedQuerySender.sendMessage(FixedQuerySender.java:124) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.jdbc.FixedQuerySender$$FastClassBySpringCGLIB$$ed3e925b.invoke(<generated>) ~[?:?]
      ... suppressed 7 lines
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      ... suppressed 10 lines
      at nl.nn.adapterframework.jdbc.FixedQuerySender$$EnhancerBySpringCGLIB$$63ddf821.sendMessage(<generated>) ~[?:?]
      at nl.nn.adapterframework.pipes.MessageSendingPipe.sendMessage(MessageSendingPipe.java:801) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.pipes.MessageSendingPipe.sendMessageWithRetries(MessageSendingPipe.java:556) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:468) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.pipes.MessageSendingPipe$$FastClassBySpringCGLIB$$b131b2cb.invoke(<generated>) ~[?:?]
      ... suppressed 8 lines
      at nl.nn.adapterframework.pipes.SenderPipe$$EnhancerBySpringCGLIB$$d22eec9b.doPipe(<generated>) ~[?:?]
      ... suppressed 21 lines
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      ... suppressed 22 lines
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      ... suppressed 25 lines
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      ... suppressed 16 lines
      at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:501) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:664) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1232) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1040) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.http.PushingListenerAdapter.processRequest(PushingListenerAdapter.java:103) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.http.rest.ApiListener.processRequest(ApiListener.java:151) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.http.rest.ApiListenerServlet.handleRequest(ApiListenerServlet.java:528) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at nl.nn.adapterframework.http.rest.ApiListenerServlet.service(ApiListenerServlet.java:202) [ibis-adapterframework-core-7.9-20230905.223421.jar:7.9-20230905.223421]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:583) [servlet-api.jar:?]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212) [catalina.jar:8.5.90]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) [catalina.jar:8.5.90]
      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-websocket.jar:8.5.90]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181) [catalina.jar:8.5.90]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) [catalina.jar:8.5.90]
      ... suppressed 15 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.29.jar:5.3.29]
      ... suppressed 5 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.29.jar:5.3.29]
      ... suppressed 2 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.29.jar:5.3.29]
      ... suppressed 3 lines
      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.29.jar:5.3.29]
      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.29.jar:5.3.29]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181) [catalina.jar:8.5.90]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) [catalina.jar:8.5.90]
      at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.20.0.jar:2.20.0]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181) [catalina.jar:8.5.90]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) [catalina.jar:8.5.90]
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) [catalina.jar:8.5.90]
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:8.5.90]
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598) [catalina.jar:8.5.90]
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:8.5.90]
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:8.5.90]
      at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682) [catalina.jar:8.5.90]
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:8.5.90]
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.90]
      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617) [tomcat-coyote.jar:8.5.90]
      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:8.5.90]
      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932) [tomcat-coyote.jar:8.5.90]
      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695) [tomcat-coyote.jar:8.5.90]
      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:8.5.90]
      at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:8.5.90]
      at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:8.5.90]
      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.90]
      at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.zip.ZipException: incorrect header check
      at java.util.zip.InflaterInputStream.read(Unknown Source) ~[?:?]
      at java.util.zip.InflaterInputStream.read(Unknown Source) ~[?:?]
      at org.apache.commons.io.input.BOMInputStream.getBOM(BOMInputStream.java:306) ~[commons-io-2.13.0.jar:2.13.0]
      at nl.nn.adapterframework.util.StreamUtil.getCharsetDetectingInputStreamReader(StreamUtil.java:145) ~[ibis-adapterframework-commons-7.9-20230905.223421.jar:?]
      at nl.nn.adapterframework.util.JdbcUtil.getBlobReader(JdbcUtil.java:283) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:?]
      at nl.nn.adapterframework.util.JdbcUtil.getBlobAsString(JdbcUtil.java:436) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:?]
      at nl.nn.adapterframework.util.JdbcUtil.getBlobAsString(JdbcUtil.java:375) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:?]
      at nl.nn.adapterframework.util.JdbcUtil.getValue(JdbcUtil.java:195) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:?]
      at nl.nn.adapterframework.util.DB2XMLWriter.getRowXml(DB2XMLWriter.java:229) ~[ibis-adapterframework-core-7.9-20230905.223421.jar:?]
      ... 200 more
```

**Comment by MLenterman** [comment]
Had the issue completely filled in already when I figured out a working solution. For me this is no longer an issue right now. Could be useful to improve error feedback though. Also wanted to report the issue anyways for other people that might run into this issue aswell.

The working solution is to simply change the column type to VARCHAR(36) instead of UUID. The H2 database RANDOM_UUID() function used to auto-generate uuid's as default value seems to still work after all (even though the documentation suggests otherwise).

**Comment by tnleeuw** [comment]
But... H2. Why?

**Comment by nielsm5** [comment]
You could try setting `blobsCompressed` to false, since you're not using blobs.

**Comment by nielsm5** [comment]
This should no longer be an issue in newer versions. If it is, please reopen this ticket or create a new one 😺.
