### ISSUE TITLE
NPE stracktraces related to CloseReportsTask in log

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#5595]
**Describe the issue**
When running with 7.8.3 stracktraces like the following appear in the log / Tomcat window:

```
19-Oct-2023 17:41:10.380 SEVERE [closeReportsScheduler-1] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler.handleError Unexpected error occurred in scheduled task
        java.lang.NullPointerException
                at nl.nn.testtool.CloseReportsTask.closeReports(CloseReportsTask.java:43)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
                at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
```

**Reporter**
Jaco de Groot

**To Reproduce**
1. Start Frank!Runner (with it's default Frank2Example1)
2. See stacktraces in Tomcat window
3. Create frank-runner.properties, add ff.version=7.8.2 and restart Frank!Runner
4. See that this time no stacktraces appear in the Tomcat window

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 7.8.3: Frank2Example1
Running on xxx using Apache Tomcat/9.0.74
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 315M, total JVM memory: 809M
Free disk space: 44GB, total disk space: 475GB
Up since: 2023-10-19 17:40:53 (1m) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by nielsm5** [comment]
This code seems to come from the [ladybug project](https://github.com/ibissource/ibis-ladybug).
