### ISSUE TITLE
Index out of bounds when downloading image

### ISSUE THREAD

**Issue by dirkjanp** [ibissource/iaf#5752]
**Describe the issue**
When downloading certain images through an apilistener adapter an StringIndexOutOfBoundsException is returned.
It concerns .png and/or .jpg file types. But there are also .png files handled succesfully.
The ibis adapter itself returns a 200 but the StringIndexOutOfBoundsException is found in the ibis.logs.

From the ladybug I took the base64 representation of the file response. Put it through https://base64.guru/converter/decode/file and the you can download the file properly.

**This is the base64 string of the file:**
iVBORw0KGgoAAAANSUhEUgAAAFYAAABWCAMAAABiiJHFAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAY1BMVEUAAAAAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsAcbsgg8Sfyua/3O5AlcxgptX///+v0+qPweFQndDP5PIQer/v9vvf7feAuN0wjMhwr9lhL2grAAAAEHRSTlMAIFCAr7/vj3AwEGCf30DPrhqFTgAAAAFiS0dEFnzRqBkAAAAJcEhZcwAAITcAACE3ATNYn3oAAAAHdElNRQfmAw4OEQGF9mFQAAACZ0lEQVRYw72Z25aqMAyGObScC1FAR0Vnv/9T7pFBRWhK09T5rwRc38pKkzRNg2BLYRQLmcAkKdMsD5gqykqBRpKDLgXgUnHoZGicwIZETYZWYCNZe7b0CbZ3cq2AoLSwMzUFmpSNwXkDZMXbQZWAg8SGI2JwU2PkVuAqk4PdqQBJ/gnqDxfxQwY86f0bAVdSF68JGwvpGtuAB0VLauqDulq2evmH3b5t9x093cwu6A+jejK3NsXW7jCJbK+a18JlFOwf2CPZ3NJQYNoH9gDu5q6M5WBf5parT8cHtQV3c9dbV/fA9g7BOwVDrvn09Uvdu+REZaiHp/PhcO7dcu031RLwrBLzAU+CsysaCs4dK9fvL91TlzEw3h/H7zsD976taV4/42sqCm+P/XEYf15vFwyb6V2LY0+34fUwnPAQK0nYGdSQLVK/Yjh2qW89NwgEC9tiWMnCInW+5mKPCDbhYQcECzysftHo2OGr6/4NGzFGxp7H1Pp+vbj5wF6nhL1uYWmR0K/2UC/YzhYrPoEtiDXBEkutYHbYRtOCesBWDruDBTbTd/dcbK1v77lYbX/Pxgqkq2FiS6QHY2IL5PjIwwqsv+VhI+zowMIq9OzAwsboSYeDnZ1Pl+ZysDE++WFg1fwwXShf2Mgw+nDHLgcgwk97v5zpFsoHtlzPajxQK910kU3VT6wqrmOLj0zt8r+dMXK4Sf6JSevWIDvzGANvgzaHOUBqM8mXVLdGdvcOGclgUXi+ehnXinT9EtqBVUm9LLIAN2To6IrMNCpOKvebuDDTh4VKo4CpOqvkLDQaEUdh4E31Xda8/+ILhMkpEMDDAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTAzLTE0VDE0OjE3OjAxKzAwOjAwCp7q8gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wMy0xNFQxNDoxNzowMSswMDowMHvDUk4AAAAASUVORK5CYII=

**This FF is used:**
FF! 7.8.1-20230420.190150

**Reporter**
Dirk-Jan

**To Reproduce**
Please contact me to reproduce the issue in our prd environment. Already called about this issue with Jeroen and Bastiaan.

**Stacktrace from ibis.log**
2023-11-14 16:18:58,029 ERROR [http-nio-8080-exec-37] {adapter=GetClaimDocumentFileAdapter} receivers.Receiver - Receiver [GetClaimDocumentFileReceiver] Exception in message processing
java.lang.StringIndexOutOfBoundsException: String index out of range: 1000
	at java.lang.String.substring(String.java:1963) ~[?:1.8.0_382]
	at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1363) [ibis-adapterframework-core-7.8.1-20230420.190150.jar:7.8.1-20230420.190150]
	at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1050) [ibis-adapterframework-core-7.8.1-20230420.190150.jar:7.8.1-20230420.190150]
	at nl.nn.adapterframework.http.PushingListenerAdapter.processRequest(PushingListenerAdapter.java:96) [ibis-adapterframework-core-7.8.1-20230420.190150.jar:7.8.1-20230420.190150]
	at nl.nn.adapterframework.http.rest.ApiListener.processRequest(ApiListener.java:142) [ibis-adapterframework-core-7.8.1-20230420.190150.jar:7.8.1-20230420.190150]
	at nl.nn.adapterframework.http.rest.ApiListenerServlet.handleRequest(ApiListenerServlet.java:559) [ibis-adapterframework-core-7.8.1-20230420.190150.jar:7.8.1-20230420.190150]
	at nl.nn.adapterframework.http.rest.ApiListenerServlet.service(ApiListenerServlet.java:189) [ibis-adapterframework-core-7.8.1-20230420.190150.jar:7.8.1-20230420.190150]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
	at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) [ibis-adapterframework-core-7.8.1-20230420.190150.jar:7.8.1-20230420.190150]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:164) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:150) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190) [spring-security-web-5.8.3.jar:5.8.3]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.20.0.jar:2.20.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.60]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.60]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660) [catalina.jar:9.0.60]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.60]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.60]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.60]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.60]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [catalina.jar:9.0.60]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-coyote.jar:9.0.60]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.60]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-coyote.jar:9.0.60]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-coyote.jar:9.0.60]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.60]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.60]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.60]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]

**Error 500 received by Postman when calling the ibis api receiver:**
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> (StringIndexOutOfBoundsException) String index out of range: 1000</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><hr class="line" /><h3>Apache Tomcat/9.0.60</h3></body></html>

**Environment**
Production

**Comment by tnleeuw** [comment]
That's a bit of an odd issue that could occur with specific data-sizes only and happens when trying to create a message for the message-status-log. Smaller images should be fine, larger images too, but there's a certain size of the result-data that could trigger this problem (depending on some other conditions too).

**Comment by dirkjanp** [comment]
So what can be done about this? We can't prevent such files of specific sizes being uploaded.

**Comment by tnleeuw** [comment]
I understand that! I just wanted to give a bit of insight into the cause of issue while I work on a fix. Unfortunately, as far as I can see there is not yet a fix for the problem in any version of the framework so I'll have to work on that ASAP.

**Comment by tnleeuw** [comment]
> So what can be done about this? We can't prevent such files of specific sizes being uploaded.

The fix for this issue is now available in 7.8.3-hotfix4, which can be downloaded from the Frank!Framework Nexus repository. You can add to the Maven project file this repository if it's not yet added already: https://nexus.frankframework.org/content/repositories/releases
