### ISSUE TITLE
exception handling in IbisTester class and javax dependecy

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#636]
**Describe the bug**
When running the IbisTester class to run larva tests in a headless ibis the runscenarios() method will run into exception that does not get logged if you do not have a dependency on javax.servlet-api version 3.0.1 The following stacktrace will occur

2020-04-23 16:40:47.691 [341M/687M] adapters started [50] from [50]
2020-04-23 16:40:47.691 [341M/687M] ***start larva***
2020-04-23 16:40:47.710 [344M/687M] null got error, retries left [1]
2020-04-23 16:40:47.712 [346M/687M] null got error, retries left [0]
nl.nn.adapterframework.util.DomBuilderException: input is null
	at nl.nn.adapterframework.util.XmlUtils.buildDomDocument(XmlUtils.java:646)
	at nl.nn.adapterframework.util.XmlUtils.evaluateXPathNumber(XmlUtils.java:2044)
	at nl.nn.adapterframework.extensions.test.IbisTester.evaluateXPathNumber(IbisTester.java:407)
	at nl.nn.adapterframework.extensions.test.IbisTester.testLarva(IbisTester.java:231)
	at nl.nn.adapterframework.extensions.test.IbisTester.doTest(IbisTester.java:119)
	at test.LarvaTest.test(LarvaTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

The adapters are started but the larva testscenarios are not run because of an exception in the runScenario() method in the IbisTester class. After debugging we found that the error occured because of a missing  javax.servlet-api-3.0.1.jar. But this should have been logged at line 355 --> 
     debug(scenarioInfo + " got error, retries left [" + count + "]**, e**");
This dependency is needed to create a MockHttpServletRequest when constructing the ScenarioRunner

This was solved by adding a dependency on javax.servlet-api version 3.0.1. Also this dependency should be included when depending on ibis-adapterframework-larva. 

This is iaf version 7.6-20200317.120259.

**Category**
 - Frank Framework

**To Reproduce**
Have a ibis config with larvatest and run them headless through IbisTester, while having a dependency on 

		<dependency>
			<artifactId>servlet-api</artifactId>
			<groupId>javax.servlet</groupId>
			<version>2.5</version>
			<scope>test</scope>
		</dependency>
instead of 
		<dependency>
		   <artifactId>javax.servlet-api</artifactId>
		   <groupId>javax.servlet</groupId>
		   <version>3.0.1</version>
		   <scope>test</scope>
		</dependency>

**Expected behavior**
The headless ibis should be able to find the scenarios and run them or a proper error is given in case of missing classes.
When depending on ibis-adapterframework-larva not having to depend also on seperate javax.servlet-api

**Screenshots**

**Environment:**
local windows laptop

**Comment by nielsm5** [comment]
If you use custom code, it is strongly advised to also use an IDE capable of compiling this code. You would have noticed the errors in the outdated pom file, a lot quicker!
