### ISSUE TITLE
null pointer when mapping an xml to json with 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#753]
**Describe the bug**
2020-05-25 15:56:55,348 ERROR [http-bio-80-exec-5] [mid [0a7219fe--515f9001_1724c1c1f4a_-7ffe]] core.Adapter - Adapter [GetDocumentAndAttributes_4 (REST)] error processing message with messageId [0a7219fe--515f9001_1724c1c1f4a_-7ffe]:
nl.nn.adapterframework.core.ListenerException: Uncaught runtime exception running pipe 'Response_To_Json': (NullPointerException)
      at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:697) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.receivers.ReceiverBase.processMessageInAdapter(ReceiverBase.java:1168) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.receivers.ReceiverBase.processRequest(ReceiverBase.java:905) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.receivers.ReceiverBase.processRequest(ReceiverBase.java:886) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.http.PushingListenerAdapter.processRequest(PushingListenerAdapter.java:86) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.http.rest.ApiListener.processRequest(ApiListener.java:93) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.http.rest.ApiListenerServlet.service(ApiListenerServlet.java:448) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:?]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.100]
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165) [catalina.jar:7.0.100]
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104) [catalina.jar:7.0.100]
      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.100]
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452) [catalina.jar:7.0.100]
      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1195) [tomcat-coyote.jar:7.0.100]
      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654) [tomcat-coyote.jar:7.0.100]
      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317) [tomcat-coyote.jar:7.0.100]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.100]
      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: nl.nn.adapterframework.core.PipeRunException: Uncaught runtime exception running pipe 'Response_To_Json': (NullPointerException)
      at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:92) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:174) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:96) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:105) ~[ibis-adapterframework-ladybug-7.6-20200525.101351.jar:7.6-20200525.101351]
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$527713e4.processPipeLine(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:70) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:49) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:39) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:48) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:536) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:673) [ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      ... 33 more
Caused by: java.lang.NullPointerException
      at nl.nn.adapterframework.pipes.Json2XmlValidator.addNamespace(Json2XmlValidator.java:272) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.pipes.Json2XmlValidator.doPipe(Json2XmlValidator.java:150) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.pipes.XmlValidator.doPipe(XmlValidator.java:210) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CorePipeProcessor.processPipe(CorePipeProcessor.java:32) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CheckMessageSizePipeProcessor.processPipe(CheckMessageSizePipeProcessor.java:37) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.LockerPipeProcessor.processPipe(LockerPipeProcessor.java:60) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.processPipe(TransactionAttributePipeProcessor.java:61) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:57) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$FastClassBySpringCGLIB$$3159a29c.invoke(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:96) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:160) ~[ibis-adapterframework-ladybug-7.6-20200525.101351.jar:7.6-20200525.101351]
      at sun.reflect.GeneratedMethodAccessor331.invoke(Unknown Source) ~[?:?]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$EnhancerBySpringCGLIB$$6baaf069.processPipe(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:81) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$FastClassBySpringCGLIB$$feb9be85.invoke(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:96) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:132) ~[ibis-adapterframework-ladybug-7.6-20200525.101351.jar:7.6-20200525.101351]
      at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source) ~[?:?]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$6fc37dc4.processPipe(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:81) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:174) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:96) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:105) ~[ibis-adapterframework-ladybug-7.6-20200525.101351.jar:7.6-20200525.101351]
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
      at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$527713e4.processPipeLine(<generated>) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:70) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:49) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:39) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:48) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:536) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:673) ~[ibis-adapterframework-core-7.6-20200525.101351.jar:7.6-20200525.101351]
      ... 33 more
`    <Json2XmlValidatorPipe name="Response_To_Json" 
				outputFormat="json" 
				acceptNamespaceLessXml="true" 
				schema="GetDocumentAndAttributes_4/xsd/Archiving_Document_4_GetDocumentAndAttributes_1_flattened.xsd" 
				root="GetDocumentAndAttributes_Response">

                <Forward name="success" path="READY" />
                <Forward name="failure" path="ServerError" />
            </Json2XmlValidatorPipe>`

**Category**
 - Frank Framework

**To Reproduce**
seems to go wrong in latest update of IAF

**Expected behavior**
a json output 

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty)
 - IAF Version [e.g. 7.4]

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
getest op test omgeving tegen IAF 7.6-20200330.192854
zelfde fout 
ibis4titan SI test
[Pipeline GetDocumentAndAttributes_4 (REST).zip](https://github.com/ibissource/iaf/files/4677751/Pipeline.GetDocumentAndAttributes_4.REST.zip)
