### ISSUE TITLE
Ladybug crash on changing Report generator enabled with Java 2 security enabled

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#767]
**Describe the bug**
When changing Report generator enabled with Java 2 security enabled the status of the Report generator is changed but Ladybug gives an error and resets itself.

**Reporter**
Jaco de Groot

**Category**
 - Ladybug (debugging tool)

**To Reproduce**
1. Go to the Ladybug
2. Click on Options...
3. Change Report generator enabled
4. See error: An application error has occurred.  Your session has been reset.

**Expected behavior**
Wouldn't expect to see an error message

**Screenshots**
-

**Environment:**
 - WebSphere (in A and P where Java 2 Security is enabled)
 - Chrome and Firefox
 - IAF 7.5 RC2 (also saw it on IAF 7.4)

**Additional context**
This happens when Ladybug tries to log who changed this setting to the security log:

				msg = msg + " by" + echo2Application.getCommandIssuedBy();
				secLog.info(msg);

See stacktrace also:

[28-5-20 14:22:11:348 CEST] 00000846 webapp E com.ibm.ws.webcontainer.webapp.WebApp logServletError SRVE0293E: [Servlet Error]-[TestToolServlet]: java.security.AccessControlException: Access denied ("java.security.SecurityPermission" "printIdentity")
      at java.security.AccessController.throwACE(AccessController.java:176)
      at java.security.AccessController.checkPermissionHelper(AccessController.java:237)
      at java.security.AccessController.checkPermission(AccessController.java:373)
      at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
      at com.ibm.ws.security.core.SecurityManager.checkPermission(SecurityManager.java:208)
      at java.lang.SecurityManager.checkSecurityAccess(SecurityManager.java:1879)
      at <unknown class>.<unknown method>(Unknown Source)
      at <unknown class>.<unknown method>(Unknown Source)
      at java.lang.String.valueOf(String.java:3416)
      at java.lang.StringBuilder.append(StringBuilder.java:516)
      at nl.nn.testtool.echo2.Echo2Application.getCommandIssuedBy(Echo2Application.java:635)
      at nl.nn.testtool.echo2.reports.ReportsComponent.actionPerformed(ReportsComponent.java:613)
      at nextapp.echo2.app.list.AbstractListComponent.fireActionEvent(AbstractListComponent.java:176)
      at nextapp.echo2.app.list.AbstractListComponent.processInput(AbstractListComponent.java:377)
      at nextapp.echo2.app.update.ClientUpdateManager.process(ClientUpdateManager.java:116)
      at nextapp.echo2.app.update.UpdateManager.processClientUpdates(UpdateManager.java:89)
      at nextapp.echo2.webcontainer.ContainerSynchronizeService.renderUpdate(ContainerSynchronizeService.java:471)
      at nextapp.echo2.webrender.service.SynchronizeService.service(SynchronizeService.java:279)
      at nextapp.echo2.webrender.WebRenderServlet.process(WebRenderServlet.java:273)
      at nextapp.echo2.webrender.WebRenderServlet.doPost(WebRenderServlet.java:189)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1233)
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:782)
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:481)
      at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136)
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:97)
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226)
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967)
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107)
      at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87)
      at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:949)
      at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
      at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:213)
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
      at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
      at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)
      at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
      at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
      at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
      at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
      at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
      at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
      at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)

**Comment by nielsm5** [comment]
Als het goed is moet deze gewoon in de was.policy staan.. is dit toevallig niet up2date?

**Comment by jacodg** [comment]
Opened a feature request to have an ibis-ear-plugin to make sure every project has a correct was.policy. See: #1123
