### ISSUE TITLE
When Ibis4Test boots in Eclipse, it produces an error message

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#782]
**Describe the bug**
When you run Ibis4Test in Eclipse, you see an error "IbisContext failed to initialize", with a stack trace. The stack trace is shown below. The application does start, however and you can run the Larva tests.

Jun 02, 2020 4:04:04 PM org.apache.catalina.core.ApplicationContext log
INFO: Starting IbisContext
Jun 02, 2020 4:04:04 PM org.apache.catalina.core.ApplicationContext log
SEVERE: IbisContext failed to initialize
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'proxiedDataSources' defined in class path resource [springTOMCAT.xml]: Could not resolve placeholder 'jdbc.datasource.oracle_docker' in value "${jdbc.datasource.oracle_docker}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'jdbc.datasource.oracle_docker' in value "${jdbc.datasource.oracle_docker}"
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:223)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.processProperties(PropertySourcesPlaceholderConfigurer.java:180)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:152)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:163)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at nl.nn.adapterframework.lifecycle.IbisApplicationContext.createApplicationContext(IbisApplicationContext.java:118)
	at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:121)
	at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:101)
	at nl.nn.adapterframework.lifecycle.IbisApplicationServlet.init(IbisApplicationServlet.java:75)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1240)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1184)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1078)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5389)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5689)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1689)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1679)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'jdbc.datasource.oracle_docker' in value "${jdbc.datasource.oracle_docker}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:204)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitMap(BeanDefinitionVisitor.java:259)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:198)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitGenericArgumentValues(BeanDefinitionVisitor.java:159)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:85)
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:220)
	... 23 more

Jun 02, 2020 4:04:07 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://jakarta.apache.org/struts/tags-bean is already defined

**Reporter**
Martijn Dirkse

**Category**
 - Frank Framework

**To Reproduce**
1. Apply CONTRIBUTING.md and TESTING_WITH_IAF-TEST.md to set up Ibis4Test. Configure to use a Dockerized Oracle database as explained in the applicable README.md files.
2. Start the Tomcat server configured in Eclipse.
3. Watch Standard Output as written to the Console window of Eclipse.

**Expected behavior**
No error message is printed to standard output when you start the application server.

**Screenshots**

**Environment:**
 - Tomcat version 7.0.103. Java 8.
 - Commit 473c834cbc3f640d8042331814423fd70276cea2. Version is shown in the browser as "IAF 7.6-SNAPSHOT".

**Additional context**
Until we understand this error, we cannot be sure that the tests are doing what we expect from them.

**Comment by mhdirkse** [comment]
I saw that the properties to select the database have been reorganized. I do not have the issue anymore.
