### ISSUE TITLE
RestSender does not work properly

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#893]
**Describe the bug**
I have a RestSender in my Frank config. It produces a NullPointerException when the adapter is configured. With stub4testtool.configuration=true, this problem does not occur.

**Reporter**
Martijn Dirkse

**Category**
 - Frank Framework

**To Reproduce**
1. Start the following configuration with the Frank!Runner: [hermesBridge.zip](https://github.com/ibissource/iaf/files/4853206/hermesBridge.zip). Keep your `classes` and `tests` directories empty.
2. In the Adapter Status page, look at the errors. You see: "ERROR: error initializing pipeline: Exception configuring Pipe [pipeCallConscience]: (NullPointerException)".
3. Go to the logs. You see the following Java exception:
```
      2020-06-30 18:16:10,174 DEBUG [http-bio-80-exec-1] null core.PipeLine - PipeLine of [adapterToConscience] configuring Pipe [pipeCallConscience]
      2020-06-30 18:16:10,178 ERROR [http-bio-80-exec-1] null core.Adapter - Adapter [adapterToConscience] error initializing pipeline
        nl.nn.adapterframework.configuration.ConfigurationException: Exception configuring Pipe [pipeCallConscience]: (NullPointerException)
          at nl.nn.adapterframework.core.PipeLine.configure(PipeLine.java:411) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.core.PipeLine.configure(PipeLine.java:262) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.core.Adapter.configure(Adapter.java:186) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.BasicAdapterServiceImpl.registerAdapter(BasicAdapterServiceImpl.java:32) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.Configuration.registerAdapter(Configuration.java:256) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
          at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
          at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:281) [commons-beanutils-1.8.0.jar:1.8.0]
          at org.apache.commons.digester.SetNextRule.end(SetNextRule.java:217) [commons-digester-1.8.1.jar:1.8.1]
          at org.apache.commons.digester.Rule.end(Rule.java:253) [commons-digester-1.8.1.jar:1.8.1]
          at org.apache.commons.digester.Digester.endElement(Digester.java:1233) [commons-digester-1.8.1.jar:1.8.1]
          at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
          at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:2.12.1-xml-schema-1.1]
          at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:2.12.1-xml-schema-1.1]
          at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:2.12.1-xml-schema-1.1]
          at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
          at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
          at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
          at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
          at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) [ibis-xerces-2.12.1-xml-schema-1.1.jar:?]
          at org.apache.commons.digester.Digester.parse(Digester.java:1812) [commons-digester-1.8.1.jar:1.8.1]
          at nl.nn.adapterframework.configuration.ConfigurationDigester.digestConfiguration(ConfigurationDigester.java:236) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.ConfigurationDigester.digestConfiguration(ConfigurationDigester.java:196) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.IbisContext.digestClassLoaderConfiguration(IbisContext.java:369) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:308) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:259) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:141) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:101) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.configuration.IbisContext.fullReload(IbisContext.java:249) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.unmanaged.DefaultIbisManager.handleAdapter(DefaultIbisManager.java:251) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.webcontrol.api.ShowConfiguration.fullReload(ShowConfiguration.java:125) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
          at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
          at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180) [cxf-core-3.1.18.jar:3.1.18]
          at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.1.18.jar:3.1.18]
          at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
          at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
          at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.1.18.jar:3.1.18]
          at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.1.18.jar:3.1.18]
          at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309) [cxf-core-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:239) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) [servlet-api.jar:?]
          at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.100]
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
          at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.100]
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
          at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
          at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) [ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
          at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:7.0.100]
          at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.100]
          at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492) [catalina.jar:7.0.100]
          at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165) [catalina.jar:7.0.100]
          at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104) [catalina.jar:7.0.100]
          at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025) [catalina.jar:7.0.100]
          at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.100]
          at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452) [catalina.jar:7.0.100]
          at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1195) [tomcat-coyote.jar:7.0.100]
          at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654) [tomcat-coyote.jar:7.0.100]
          at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:319) [tomcat-coyote.jar:7.0.100]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
          at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.100]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
      Caused by: java.lang.NullPointerException
          at nl.nn.adapterframework.http.HttpSenderBase.getURI(HttpSenderBase.java:257) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.http.HttpSenderBase.configure(HttpSenderBase.java:328) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.http.HttpSender.configure(HttpSender.java:178) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.http.HttpSender$$FastClassBySpringCGLIB$$5435e802.invoke(<generated>) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at nl.nn.adapterframework.http.RestSender$$EnhancerBySpringCGLIB$$b368266.configure(<generated>) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.pipes.MessageSendingPipe.configure(MessageSendingPipe.java:303) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.pipes.AbstractPipe.configure(AbstractPipe.java:205) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.pipes.AbstractPipe$$FastClassBySpringCGLIB$$2e2d3d9a.invoke(<generated>) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
          at nl.nn.adapterframework.pipes.GenericMessageSendingPipe$$EnhancerBySpringCGLIB$$ee74c1c6.configure(<generated>) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          at nl.nn.adapterframework.core.PipeLine.configure(PipeLine.java:363) ~[ibis-adapterframework-core-7.6-20200629.103527.jar:7.6-20200629.103527]
          ... 79 more
```
**Expected behavior**
At least I want a clear error message if 

**Screenshots**

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - FF! 7.6-20200629.103527

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by mhdirkse** [comment]
I did not nicely format the Java stack trace. Please search for "Caused by: java.lang.NullPointerException" to find the right spot.

**Comment by nielsm5** [comment]
You have a relative path instead of an absolute path.

**Comment by nielsm5** [comment]
I've added a fix for the NPE as this happens to all HttpSenders

**Comment by mhdirkse** [comment]
I still have the problem in version 7.6-20200701.142340.

**Comment by mhdirkse** [comment]
Verified.
