### ISSUE TITLE
Browsing message logs does not work with a H2 database

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#932]
**Describe the bug**
I have a Frank configuration with a message log backed by table ibisstore. Both the Frank!Console and an MessageStoreListener fail to read from the queue.

**Reporter**
Martijn Dirkse

**Category**
 - Frank Framework

**To Reproduce**
1. Start the Frank!Runner with Frank2Example3.
2. Using Test Pipeline, issue an arbitrary message to Adapter 01.
3. Read the message log of adapter 1. You see an error in the Frank!Console about a JdbcSQLNonTransientException.
4. Look at the logfile. Adapter 03 fails to read the message from the message store.

**Expected behavior**
You do not see the error in the Frank!Console, and Adapter 03 can read the message from the message store.

**Screenshots**
I have the part of the logfile that shows the error of Adapter 03.

2020-07-14 17:19:00,299 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] [mid [1]] core.Adapter - Adapter [03 TestMessageStoreListenerAndErrorStorage] messageId [1] duration [10ms] got exit-state [success] and result [String: message 1] from PipeLine
2020-07-14 17:19:00,299 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] [mid [1]] core.Adapter - Adapter: [03 TestMessageStoreListenerAndErrorStorage] STAT: Finished processing message with messageId [1] exit-state [success] started 2020-07-14 17:19:00.288 finished 2020-07-14 17:19:00.299 total duration: 11 msecs
2020-07-14 17:19:00,299 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] null receivers.GenericReceiver - Receiver [TestMessageStoreListenerAndErrorStorage] received result: exitState [success], result [message 1]
2020-07-14 17:19:00,299 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] null receivers.GenericReceiver - Receiver [TestMessageStoreListenerAndErrorStorage] canceling TimeoutGuard, isInterrupted [false]
2020-07-14 17:19:00,299 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] null receivers.GenericReceiver - Receiver [TestMessageStoreListenerAndErrorStorage] caching first result for messageId [1]
2020-07-14 17:19:00,301 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] null jdbc.MessageStoreListener - setting parameter 1 to [1]
2020-07-14 17:19:00,303 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] null receivers.GenericReceiver - Receiver [TestMessageStoreListenerAndErrorStorage] finishes processing message
2020-07-14 17:19:00,303 DEBUG [TestMessageStoreListenerAndErrorStorage-listener[1]] null receivers.GenericReceiver - Receiver [TestMessageStoreListenerAndErrorStorage] messageId [1] correlationId [1] returning result [message 1]
2020-07-14 17:19:08,898 DEBUG [http-bio-80-exec-2] null flow.FlowDiagramManager - retrieve flow file for name[_ALL_] in folder[build\apache-tomcat-7.0.100\temp\Frank2Example3\flow\config]
2020-07-14 17:19:12,420 DEBUG [http-bio-80-exec-2] null flow.FlowDiagramManager - retrieve flow file for name[01 TestMessageLog] in folder[build\apache-tomcat-7.0.100\temp\Frank2Example3\flow\adapter]
2020-07-14 17:19:15,890 DEBUG [http-bio-80-exec-2] null jdbc.JdbcTransactionalStorage - preparing selectListQuery [SELECT MESSAGEKEY,MESSAGEID,CORRELATIONID,MESSAGEDATE,EXPIRYDATE,TYPE,HOST,LABEL,COMMENTS FROM IBISSTORE WHERE SLOTID=? AND TYPE=? ORDER BY MESSAGEDATE DESC ]
2020-07-14 17:19:15,894 ERROR [http-bio-80-exec-2] null api.ApiException - (JdbcSQLNonTransientException) SQLState [90007], errorCode [90007]: The object is already closed [90007-200]
nl.nn.adapterframework.core.ListenerException: (JdbcSQLNonTransientException) SQLState [90007], errorCode [90007]: The object is already closed [90007-200]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage$ResultSetIterator.advance(JdbcTransactionalStorage.java:972) ~[ibis-adapterframework-core-7.6-20200714.113155.jar:7.6-20200714.113155]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage$ResultSetIterator.hasNext(JdbcTransactionalStorage.java:979) ~[ibis-adapterframework-core-7.6-20200714.113155.jar:7.6-20200714.113155]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.getMessages(TransactionalStorage.java:581) [ibis-adapterframework-core-7.6-20200714.113155.jar:7.6-20200714.113155]
      at nl.nn.adapterframework.webcontrol.api.TransactionalStorage.browsePipeMessages(TransactionalStorage.java:445) [ibis-adapterframework-core-7.6-20200714.113155.jar:7.6-20200714.113155]
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
      at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101) [cxf-rt-frontend-jaxrs-3.1.18.jar:3.1.18]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:227) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:621) [servlet-api.jar:?]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278) [cxf-rt-transports-http-3.1.18.jar:3.1.18]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) [ibis-adapterframework-core-7.6-20200714.113155.jar:7.6-20200714.113155]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) [ibis-adapterframework-core-7.6-20200714.113155.jar:7.6-20200714.113155]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.100]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.100]
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165) [catalina.jar:7.0.100]
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104) [catalina.jar:7.0.100]
      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025) [catalina.jar:7.0.100]
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.100]
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452) [catalina.jar:7.0.100]
      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1195) [tomcat-coyote.jar:7.0.100]
      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654) [tomcat-coyote.jar:7.0.100]
      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:319) [tomcat-coyote.jar:7.0.100]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.100]
      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-200]
      at org.h2.message.DbException.getJdbcSQLException(DbException.java:505) ~[h2-1.4.200.jar:1.4.200]
      at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
      at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
      at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar:1.4.200]
      at org.h2.message.DbException.get(DbException.java:170) ~[h2-1.4.200.jar:1.4.200]
      at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3223) ~[h2-1.4.200.jar:1.4.200]
      at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:134) ~[h2-1.4.200.jar:1.4.200]
      at nl.nn.adapterframework.jdbc.JdbcTransactionalStorage$ResultSetIterator.advance(JdbcTransactionalStorage.java:969) ~[ibis-adapterframework-core-7.6-20200714.113155.jar:7.6-20200714.113155]
      ... 50 more

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - FF! 7.6-20200714.113155

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by mhdirkse** [comment]
Verified.
